//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Common", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright.
        /// </summary>
        internal static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;&lt;h4&gt;Copyright &amp;copy; 2009 - 2010, RapidWebDev.Org&lt;/h4&gt;&lt;/p&gt;
        ///&lt;p&gt;The copyright is owned by the organization RapidWebDev.Org. We&apos;re founded in 2004 that fully focusing on developing high efficient and performance enterprise solutions.&lt;/p&gt;.
        /// </summary>
        internal static string CopyrightContent {
            get {
                return ResourceManager.GetString("CopyrightContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashborad.
        /// </summary>
        internal static string DefaultTabTitle {
            get {
                return ResourceManager.GetString("DefaultTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception Page.
        /// </summary>
        internal static string ExceptionPageTitle {
            get {
                return ResourceManager.GetString("ExceptionPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RapidWebDev Solution.
        /// </summary>
        internal static string FramePageTitle {
            get {
                return ResourceManager.GetString("FramePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Server Error.
        /// </summary>
        internal static string InternalServerError {
            get {
                return ResourceManager.GetString("InternalServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown exception occurs in the server which has been logged. Please try to re-log into the system or contact administrators..
        /// </summary>
        internal static string InternalServerError_Message {
            get {
                return ResourceManager.GetString("InternalServerError_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        internal static string License {
            get {
                return ResourceManager.GetString("License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogOn.
        /// </summary>
        internal static string Logon {
            get {
                return ResourceManager.GetString("Logon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Log On.
        /// </summary>
        internal static string Logon_ContainerHeader {
            get {
                return ResourceManager.GetString("Logon_ContainerHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid organization credential of the user!.
        /// </summary>
        internal static string Logon_InvalidOrganizationCredential {
            get {
                return ResourceManager.GetString("Logon_InvalidOrganizationCredential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid user credential!.
        /// </summary>
        internal static string Logon_InvalidUserCredential {
            get {
                return ResourceManager.GetString("Logon_InvalidUserCredential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RapidWebDev Logon Page.
        /// </summary>
        internal static string Logon_PageTitle {
            get {
                return ResourceManager.GetString("Logon_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Logon_Password {
            get {
                return ResourceManager.GetString("Logon_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown exception occurs while logon to the system. Please contact the system administrator if possible..
        /// </summary>
        internal static string Logon_UnknowException {
            get {
                return ResourceManager.GetString("Logon_UnknowException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user is locked out by too many failed password attempts..
        /// </summary>
        internal static string Logon_UserIsLockedOut {
            get {
                return ResourceManager.GetString("Logon_UserIsLockedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Logon_UserName {
            get {
                return ResourceManager.GetString("Logon_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation Menu.
        /// </summary>
        internal static string NavigationBarTitle {
            get {
                return ResourceManager.GetString("NavigationBarTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no permission to access the resource or your authentication is expired. Please try to re-log into the system or contact administrators..
        /// </summary>
        internal static string NotAuthorized_Message {
            get {
                return ResourceManager.GetString("NotAuthorized_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Authorized Accessing.
        /// </summary>
        internal static string NotAuthorized_PageTitle {
            get {
                return ResourceManager.GetString("NotAuthorized_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The resource you&apos;re accessing is unavailable..
        /// </summary>
        internal static string PageNotFound_Message {
            get {
                return ResourceManager.GetString("PageNotFound_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Not Found.
        /// </summary>
        internal static string PageNotFound_PageTitle {
            get {
                return ResourceManager.GetString("PageNotFound_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rapid Web Development.
        /// </summary>
        internal static string RapidWebDev {
            get {
                return ResourceManager.GetString("RapidWebDev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to the default page..
        /// </summary>
        internal static string ReturnToDefaultPage {
            get {
                return ResourceManager.GetString("ReturnToDefaultPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown exception occurs in the server which has been logged. Please try to re-log into the system or contact administrators..
        /// </summary>
        internal static string UnknowException {
            get {
                return ResourceManager.GetString("UnknowException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string UploadExcel_Cancel {
            get {
                return ResourceManager.GetString("UploadExcel_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Template File.
        /// </summary>
        internal static string UploadExcel_DownloadTemplateFile {
            get {
                return ResourceManager.GetString("UploadExcel_DownloadTemplateFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel Document.
        /// </summary>
        internal static string UploadExcel_ExcelDocument {
            get {
                return ResourceManager.GetString("UploadExcel_ExcelDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The uploading excel file is not specified!.
        /// </summary>
        internal static string UploadExcel_ExcelFileIsNotSpecified {
            get {
                return ResourceManager.GetString("UploadExcel_ExcelFileIsNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The uploading file extension name is not supported!.
        /// </summary>
        internal static string UploadExcel_ExtensionFileNameIsNotSupported {
            get {
                return ResourceManager.GetString("UploadExcel_ExtensionFileNameIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel uploading page.
        /// </summary>
        internal static string UploadExcel_PageTitle {
            get {
                return ResourceManager.GetString("UploadExcel_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string UploadExcel_Save {
            get {
                return ResourceManager.GetString("UploadExcel_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        internal static string UploadExcel_Upload {
            get {
                return ResourceManager.GetString("UploadExcel_Upload", resourceCulture);
            }
        }
    }
}
