//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4200
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RapidWebDev.RestfulServices.RelationshipServices {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RelationshipObject", Namespace="http://www.rapidwebdev.org/platform")]
    [System.SerializableAttribute()]
    public partial class RelationshipObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OrdinalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid ReferenceObjectIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RelationshipTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Ordinal {
            get {
                return this.OrdinalField;
            }
            set {
                if ((this.OrdinalField.Equals(value) != true)) {
                    this.OrdinalField = value;
                    this.RaisePropertyChanged("Ordinal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ReferenceObjectId {
            get {
                return this.ReferenceObjectIdField;
            }
            set {
                if ((this.ReferenceObjectIdField.Equals(value) != true)) {
                    this.ReferenceObjectIdField = value;
                    this.RaisePropertyChanged("ReferenceObjectId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RelationshipType {
            get {
                return this.RelationshipTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.RelationshipTypeField, value) != true)) {
                    this.RelationshipTypeField = value;
                    this.RaisePropertyChanged("RelationshipType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.rapidwebdev.org/platform", ConfigurationName="RelationshipServices.RelationshipService")]
    public interface RelationshipService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rapidwebdev.org/platform/RelationshipService/SaveJson", ReplyAction="http://www.rapidwebdev.org/platform/RelationshipService/SaveJsonResponse")]
        void SaveJson(string objectXId, string objectYId, string RelationshipType, string Ordinal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rapidwebdev.org/platform/RelationshipService/SaveXml", ReplyAction="http://www.rapidwebdev.org/platform/RelationshipService/SaveXmlResponse")]
        void SaveXml(string objectXId, string objectYId, string RelationshipType, string Ordinal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rapidwebdev.org/platform/RelationshipService/RemoveJson", ReplyAction="http://www.rapidwebdev.org/platform/RelationshipService/RemoveJsonResponse")]
        void RemoveJson(string objectXId, string objectYId, string relationshipType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rapidwebdev.org/platform/RelationshipService/RemoveXml", ReplyAction="http://www.rapidwebdev.org/platform/RelationshipService/RemoveXmlResponse")]
        void RemoveXml(string objectXId, string objectYId, string relationshipType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rapidwebdev.org/platform/RelationshipService/GetOneToOneJson", ReplyAction="http://www.rapidwebdev.org/platform/RelationshipService/GetOneToOneJsonResponse")]
        RapidWebDev.RestfulServices.RelationshipServices.RelationshipObject GetOneToOneJson(string objectId, string relationshipType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rapidwebdev.org/platform/RelationshipService/GetOneToOneXml", ReplyAction="http://www.rapidwebdev.org/platform/RelationshipService/GetOneToOneXmlResponse")]
        RapidWebDev.RestfulServices.RelationshipServices.RelationshipObject GetOneToOneXml(string objectId, string relationshipType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rapidwebdev.org/platform/RelationshipService/GetManyToOneJson", ReplyAction="http://www.rapidwebdev.org/platform/RelationshipService/GetManyToOneJsonResponse")]
        RapidWebDev.RestfulServices.RelationshipServices.RelationshipObject GetManyToOneJson(string objectId, string relationshipType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rapidwebdev.org/platform/RelationshipService/GetManyToOneXml", ReplyAction="http://www.rapidwebdev.org/platform/RelationshipService/GetManyToOneXmlResponse")]
        RapidWebDev.RestfulServices.RelationshipServices.RelationshipObject GetManyToOneXml(string objectId, string relationshipType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rapidwebdev.org/platform/RelationshipService/GetOneToManyJson", ReplyAction="http://www.rapidwebdev.org/platform/RelationshipService/GetOneToManyJsonResponse")]
        RapidWebDev.RestfulServices.RelationshipServices.RelationshipObject[] GetOneToManyJson(string objectId, string relationshipType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rapidwebdev.org/platform/RelationshipService/GetOneToManyXml", ReplyAction="http://www.rapidwebdev.org/platform/RelationshipService/GetOneToManyXmlResponse")]
        RapidWebDev.RestfulServices.RelationshipServices.RelationshipObject[] GetOneToManyXml(string objectId, string relationshipType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rapidwebdev.org/platform/RelationshipService/FindAllRelationshipJson", ReplyAction="http://www.rapidwebdev.org/platform/RelationshipService/FindAllRelationshipJsonRe" +
            "sponse")]
        RapidWebDev.RestfulServices.RelationshipServices.RelationshipObject[] FindAllRelationshipJson(string objectId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rapidwebdev.org/platform/RelationshipService/FindAllRelationshipXml", ReplyAction="http://www.rapidwebdev.org/platform/RelationshipService/FindAllRelationshipXmlRes" +
            "ponse")]
        RapidWebDev.RestfulServices.RelationshipServices.RelationshipObject[] FindAllRelationshipXml(string objectId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface RelationshipServiceChannel : RapidWebDev.RestfulServices.RelationshipServices.RelationshipService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class RelationshipServiceClient : System.ServiceModel.ClientBase<RapidWebDev.RestfulServices.RelationshipServices.RelationshipService>, RapidWebDev.RestfulServices.RelationshipServices.RelationshipService {
        
        public RelationshipServiceClient() {
        }
        
        public RelationshipServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RelationshipServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RelationshipServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RelationshipServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void SaveJson(string objectXId, string objectYId, string RelationshipType, string Ordinal) {
            base.Channel.SaveJson(objectXId, objectYId, RelationshipType, Ordinal);
        }
        
        public void SaveXml(string objectXId, string objectYId, string RelationshipType, string Ordinal) {
            base.Channel.SaveXml(objectXId, objectYId, RelationshipType, Ordinal);
        }
        
        public void RemoveJson(string objectXId, string objectYId, string relationshipType) {
            base.Channel.RemoveJson(objectXId, objectYId, relationshipType);
        }
        
        public void RemoveXml(string objectXId, string objectYId, string relationshipType) {
            base.Channel.RemoveXml(objectXId, objectYId, relationshipType);
        }
        
        public RapidWebDev.RestfulServices.RelationshipServices.RelationshipObject GetOneToOneJson(string objectId, string relationshipType) {
            return base.Channel.GetOneToOneJson(objectId, relationshipType);
        }
        
        public RapidWebDev.RestfulServices.RelationshipServices.RelationshipObject GetOneToOneXml(string objectId, string relationshipType) {
            return base.Channel.GetOneToOneXml(objectId, relationshipType);
        }
        
        public RapidWebDev.RestfulServices.RelationshipServices.RelationshipObject GetManyToOneJson(string objectId, string relationshipType) {
            return base.Channel.GetManyToOneJson(objectId, relationshipType);
        }
        
        public RapidWebDev.RestfulServices.RelationshipServices.RelationshipObject GetManyToOneXml(string objectId, string relationshipType) {
            return base.Channel.GetManyToOneXml(objectId, relationshipType);
        }
        
        public RapidWebDev.RestfulServices.RelationshipServices.RelationshipObject[] GetOneToManyJson(string objectId, string relationshipType) {
            return base.Channel.GetOneToManyJson(objectId, relationshipType);
        }
        
        public RapidWebDev.RestfulServices.RelationshipServices.RelationshipObject[] GetOneToManyXml(string objectId, string relationshipType) {
            return base.Channel.GetOneToManyXml(objectId, relationshipType);
        }
        
        public RapidWebDev.RestfulServices.RelationshipServices.RelationshipObject[] FindAllRelationshipJson(string objectId) {
            return base.Channel.FindAllRelationshipJson(objectId);
        }
        
        public RapidWebDev.RestfulServices.RelationshipServices.RelationshipObject[] FindAllRelationshipXml(string objectId) {
            return base.Channel.FindAllRelationshipXml(objectId);
        }
    }
}
