//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4200
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RapidWebDev.RestfulServices.ConcreteDataServices {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AbstractExtensionBizObject", Namespace="http://www.rapidwebdev.org/platform")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RapidWebDev.RestfulServices.ConcreteDataServices.ConcreteDataObject))]
    public partial class AbstractExtensionBizObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid ExtensionDataTypeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<string, object> PropertiesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ExtensionDataTypeId {
            get {
                return this.ExtensionDataTypeIdField;
            }
            set {
                if ((this.ExtensionDataTypeIdField.Equals(value) != true)) {
                    this.ExtensionDataTypeIdField = value;
                    this.RaisePropertyChanged("ExtensionDataTypeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, object> Properties {
            get {
                return this.PropertiesField;
            }
            set {
                if ((object.ReferenceEquals(this.PropertiesField, value) != true)) {
                    this.PropertiesField = value;
                    this.RaisePropertyChanged("Properties");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConcreteDataObject", Namespace="http://www.rapidwebdev.org/platform")]
    [System.SerializableAttribute()]
    public partial class ConcreteDataObject : RapidWebDev.RestfulServices.ConcreteDataServices.AbstractExtensionBizObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid CreatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RapidWebDev.RestfulServices.ConcreteDataServices.DeleteStatus DeleteStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.Guid> LastUpdatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> LastUpdatedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid CreatedBy {
            get {
                return this.CreatedByField;
            }
            set {
                if ((this.CreatedByField.Equals(value) != true)) {
                    this.CreatedByField = value;
                    this.RaisePropertyChanged("CreatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedDate {
            get {
                return this.CreatedDateField;
            }
            set {
                if ((this.CreatedDateField.Equals(value) != true)) {
                    this.CreatedDateField = value;
                    this.RaisePropertyChanged("CreatedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RapidWebDev.RestfulServices.ConcreteDataServices.DeleteStatus DeleteStatus {
            get {
                return this.DeleteStatusField;
            }
            set {
                if ((this.DeleteStatusField.Equals(value) != true)) {
                    this.DeleteStatusField = value;
                    this.RaisePropertyChanged("DeleteStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> LastUpdatedBy {
            get {
                return this.LastUpdatedByField;
            }
            set {
                if ((this.LastUpdatedByField.Equals(value) != true)) {
                    this.LastUpdatedByField = value;
                    this.RaisePropertyChanged("LastUpdatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> LastUpdatedDate {
            get {
                return this.LastUpdatedDateField;
            }
            set {
                if ((this.LastUpdatedDateField.Equals(value) != true)) {
                    this.LastUpdatedDateField = value;
                    this.RaisePropertyChanged("LastUpdatedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeleteStatus", Namespace="http://www.rapidwebdev.org/platform")]
    public enum DeleteStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotDeleted = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Deleted = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="EnumerationValueCollection", Namespace="http://schemas.datacontract.org/2004/07/RapidWebDev.ExtensionModel", ItemName="EnumerationValue")]
    [System.SerializableAttribute()]
    public class EnumerationValueCollection : System.Collections.Generic.List<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DateTimeFieldValue", Namespace="http://www.rapidwebdev.org/extensionmodel")]
    [System.SerializableAttribute()]
    public partial class DateTimeFieldValue : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateTimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateTime {
            get {
                return this.DateTimeField;
            }
            set {
                if ((this.DateTimeField.Equals(value) != true)) {
                    this.DateTimeField = value;
                    this.RaisePropertyChanged("DateTime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DecimalFieldValue", Namespace="http://www.rapidwebdev.org/extensionmodel")]
    [System.SerializableAttribute()]
    public partial class DecimalFieldValue : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal DecimalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Decimal {
            get {
                return this.DecimalField;
            }
            set {
                if ((this.DecimalField.Equals(value) != true)) {
                    this.DecimalField = value;
                    this.RaisePropertyChanged("Decimal");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StringFieldValue", Namespace="http://www.rapidwebdev.org/extensionmodel")]
    [System.SerializableAttribute()]
    public partial class StringFieldValue : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string String {
            get {
                return this.StringField;
            }
            set {
                if ((object.ReferenceEquals(this.StringField, value) != true)) {
                    this.StringField = value;
                    this.RaisePropertyChanged("String");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IntegerFieldValue", Namespace="http://www.rapidwebdev.org/extensionmodel")]
    [System.SerializableAttribute()]
    public partial class IntegerFieldValue : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IntegerField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Integer {
            get {
                return this.IntegerField;
            }
            set {
                if ((this.IntegerField.Equals(value) != true)) {
                    this.IntegerField = value;
                    this.RaisePropertyChanged("Integer");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ConcreteDataQueryResult", Namespace="http://www.rapidwebdev.org/platform", ItemName="ConcreteDataObject")]
    [System.SerializableAttribute()]
    public class ConcreteDataQueryResult : System.Collections.Generic.List<RapidWebDev.RestfulServices.ConcreteDataServices.ConcreteDataObject> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WebServiceQueryPredicate", Namespace="http://www.rapidwebdev.org/common")]
    [System.SerializableAttribute()]
    public partial class WebServiceQueryPredicate : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExpressionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RapidWebDev.RestfulServices.ConcreteDataServices.WebServiceQueryPredicateParameter[] ParametersField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Expression {
            get {
                return this.ExpressionField;
            }
            set {
                if ((object.ReferenceEquals(this.ExpressionField, value) != true)) {
                    this.ExpressionField = value;
                    this.RaisePropertyChanged("Expression");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RapidWebDev.RestfulServices.ConcreteDataServices.WebServiceQueryPredicateParameter[] Parameters {
            get {
                return this.ParametersField;
            }
            set {
                if ((object.ReferenceEquals(this.ParametersField, value) != true)) {
                    this.ParametersField = value;
                    this.RaisePropertyChanged("Parameters");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WebServiceQueryPredicateParameter", Namespace="http://www.rapidwebdev.org/common")]
    [System.SerializableAttribute()]
    public partial class WebServiceQueryPredicateParameter : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RapidWebDev.RestfulServices.ConcreteDataServices.WebServiceQueryPredicateParameterTypes TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RapidWebDev.RestfulServices.ConcreteDataServices.WebServiceQueryPredicateParameterTypes Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WebServiceQueryPredicateParameterTypes", Namespace="http://www.rapidwebdev.org/common")]
    public enum WebServiceQueryPredicateParameterTypes : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        String = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DateTime = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Guid = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Integer = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Decimal = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Double = 5,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.rapidwebdev.org/platform", ConfigurationName="ConcreteDataServices.ConcreteDataService")]
    public interface ConcreteDataService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rapidwebdev.org/platform/ConcreteDataService/SaveJson", ReplyAction="http://www.rapidwebdev.org/platform/ConcreteDataService/SaveJsonResponse")]
        string SaveJson(RapidWebDev.RestfulServices.ConcreteDataServices.ConcreteDataObject concreteDataObject);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rapidwebdev.org/platform/ConcreteDataService/SaveXml", ReplyAction="http://www.rapidwebdev.org/platform/ConcreteDataService/SaveXmlResponse")]
        string SaveXml(RapidWebDev.RestfulServices.ConcreteDataServices.ConcreteDataObject concreteDataObject);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rapidwebdev.org/platform/ConcreteDataService/GetByIdJson", ReplyAction="http://www.rapidwebdev.org/platform/ConcreteDataService/GetByIdJsonResponse")]
        RapidWebDev.RestfulServices.ConcreteDataServices.ConcreteDataObject GetByIdJson(string concreteDataId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rapidwebdev.org/platform/ConcreteDataService/GetByIdXml", ReplyAction="http://www.rapidwebdev.org/platform/ConcreteDataService/GetByIdXmlResponse")]
        RapidWebDev.RestfulServices.ConcreteDataServices.ConcreteDataObject GetByIdXml(string concreteDataId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rapidwebdev.org/platform/ConcreteDataService/GetByNameJson", ReplyAction="http://www.rapidwebdev.org/platform/ConcreteDataService/GetByNameJsonResponse")]
        RapidWebDev.RestfulServices.ConcreteDataServices.ConcreteDataObject GetByNameJson(string type, string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rapidwebdev.org/platform/ConcreteDataService/GetByNameXml", ReplyAction="http://www.rapidwebdev.org/platform/ConcreteDataService/GetByNameXmlResponse")]
        RapidWebDev.RestfulServices.ConcreteDataServices.ConcreteDataObject GetByNameXml(string type, string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rapidwebdev.org/platform/ConcreteDataService/FindByKeywordJson", ReplyAction="http://www.rapidwebdev.org/platform/ConcreteDataService/FindByKeywordJsonResponse" +
            "")]
        RapidWebDev.RestfulServices.ConcreteDataServices.ConcreteDataObject[] FindByKeywordJson(string concreteDataType, string query, int limit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rapidwebdev.org/platform/ConcreteDataService/FindByKeywordXml", ReplyAction="http://www.rapidwebdev.org/platform/ConcreteDataService/FindByKeywordXmlResponse")]
        RapidWebDev.RestfulServices.ConcreteDataServices.ConcreteDataObject[] FindByKeywordXml(string concreteDataType, string query, int limit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rapidwebdev.org/platform/ConcreteDataService/FindConcreteDataTypesJson" +
            "", ReplyAction="http://www.rapidwebdev.org/platform/ConcreteDataService/FindConcreteDataTypesJson" +
            "Response")]
        string[] FindConcreteDataTypesJson();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rapidwebdev.org/platform/ConcreteDataService/FindConcreteDataTypesXml", ReplyAction="http://www.rapidwebdev.org/platform/ConcreteDataService/FindConcreteDataTypesXmlR" +
            "esponse")]
        string[] FindConcreteDataTypesXml();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rapidwebdev.org/platform/ConcreteDataService/QueryConcreteDataJson", ReplyAction="http://www.rapidwebdev.org/platform/ConcreteDataService/QueryConcreteDataJsonResp" +
            "onse")]
        RapidWebDev.RestfulServices.ConcreteDataServices.ConcreteDataQueryResult QueryConcreteDataJson(string orderby, int pageIndex, int pageSize, RapidWebDev.RestfulServices.ConcreteDataServices.WebServiceQueryPredicate predicate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rapidwebdev.org/platform/ConcreteDataService/QueryConcreteDataXml", ReplyAction="http://www.rapidwebdev.org/platform/ConcreteDataService/QueryConcreteDataXmlRespo" +
            "nse")]
        RapidWebDev.RestfulServices.ConcreteDataServices.ConcreteDataQueryResult QueryConcreteDataXml(string orderby, int pageIndex, int pageSize, RapidWebDev.RestfulServices.ConcreteDataServices.WebServiceQueryPredicate predicate);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface ConcreteDataServiceChannel : RapidWebDev.RestfulServices.ConcreteDataServices.ConcreteDataService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class ConcreteDataServiceClient : System.ServiceModel.ClientBase<RapidWebDev.RestfulServices.ConcreteDataServices.ConcreteDataService>, RapidWebDev.RestfulServices.ConcreteDataServices.ConcreteDataService {
        
        public ConcreteDataServiceClient() {
        }
        
        public ConcreteDataServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConcreteDataServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConcreteDataServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConcreteDataServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string SaveJson(RapidWebDev.RestfulServices.ConcreteDataServices.ConcreteDataObject concreteDataObject) {
            return base.Channel.SaveJson(concreteDataObject);
        }
        
        public string SaveXml(RapidWebDev.RestfulServices.ConcreteDataServices.ConcreteDataObject concreteDataObject) {
            return base.Channel.SaveXml(concreteDataObject);
        }
        
        public RapidWebDev.RestfulServices.ConcreteDataServices.ConcreteDataObject GetByIdJson(string concreteDataId) {
            return base.Channel.GetByIdJson(concreteDataId);
        }
        
        public RapidWebDev.RestfulServices.ConcreteDataServices.ConcreteDataObject GetByIdXml(string concreteDataId) {
            return base.Channel.GetByIdXml(concreteDataId);
        }
        
        public RapidWebDev.RestfulServices.ConcreteDataServices.ConcreteDataObject GetByNameJson(string type, string name) {
            return base.Channel.GetByNameJson(type, name);
        }
        
        public RapidWebDev.RestfulServices.ConcreteDataServices.ConcreteDataObject GetByNameXml(string type, string name) {
            return base.Channel.GetByNameXml(type, name);
        }
        
        public RapidWebDev.RestfulServices.ConcreteDataServices.ConcreteDataObject[] FindByKeywordJson(string concreteDataType, string query, int limit) {
            return base.Channel.FindByKeywordJson(concreteDataType, query, limit);
        }
        
        public RapidWebDev.RestfulServices.ConcreteDataServices.ConcreteDataObject[] FindByKeywordXml(string concreteDataType, string query, int limit) {
            return base.Channel.FindByKeywordXml(concreteDataType, query, limit);
        }
        
        public string[] FindConcreteDataTypesJson() {
            return base.Channel.FindConcreteDataTypesJson();
        }
        
        public string[] FindConcreteDataTypesXml() {
            return base.Channel.FindConcreteDataTypesXml();
        }
        
        public RapidWebDev.RestfulServices.ConcreteDataServices.ConcreteDataQueryResult QueryConcreteDataJson(string orderby, int pageIndex, int pageSize, RapidWebDev.RestfulServices.ConcreteDataServices.WebServiceQueryPredicate predicate) {
            return base.Channel.QueryConcreteDataJson(orderby, pageIndex, pageSize, predicate);
        }
        
        public RapidWebDev.RestfulServices.ConcreteDataServices.ConcreteDataQueryResult QueryConcreteDataXml(string orderby, int pageIndex, int pageSize, RapidWebDev.RestfulServices.ConcreteDataServices.WebServiceQueryPredicate predicate) {
            return base.Channel.QueryConcreteDataXml(orderby, pageIndex, pageSize, predicate);
        }
    }
}
