//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RapidWebDev.Platform.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RapidWebDev.Platform.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anonymous.
        /// </summary>
        internal static string AnonymousUser {
            get {
                return ResourceManager.GetString("AnonymousUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The organization type {1} cannot be deleted due to {0} associated organizations..
        /// </summary>
        internal static string CannotDeleteOrganizationTypeWithOrganizations {
            get {
                return ResourceManager.GetString("CannotDeleteOrganizationTypeWithOrganizations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code cannot be updated..
        /// </summary>
        internal static string CodeCannotUpdate {
            get {
                return ResourceManager.GetString("CodeCannotUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concrete data name cannot be empty!.
        /// </summary>
        internal static string ConcreteDataNameCannotBeEmpty {
            get {
                return ResourceManager.GetString("ConcreteDataNameCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concrete Data Object cannot be null!.
        /// </summary>
        internal static string ConcreteDataObjectCannotBeNull {
            get {
                return ResourceManager.GetString("ConcreteDataObjectCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display name cannot be empty!.
        /// </summary>
        internal static string DisplayNameCannotBeEmpty {
            get {
                return ResourceManager.GetString("DisplayNameCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name &quot;{0}&quot; of concrete data is duplicated..
        /// </summary>
        internal static string DuplicateConcreteDataName {
            get {
                return ResourceManager.GetString("DuplicateConcreteDataName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display name {0} has existed already!.
        /// </summary>
        internal static string DuplicateDisplayName {
            get {
                return ResourceManager.GetString("DuplicateDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate hierarchy data name..
        /// </summary>
        internal static string DuplicateHierarchyDataName {
            get {
                return ResourceManager.GetString("DuplicateHierarchyDataName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate hierarchy type name..
        /// </summary>
        internal static string DuplicateHierarchyTypeName {
            get {
                return ResourceManager.GetString("DuplicateHierarchyTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization code {0} has existed already!.
        /// </summary>
        internal static string DuplicateOrganizationCode {
            get {
                return ResourceManager.GetString("DuplicateOrganizationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization name {0} has existed already!.
        /// </summary>
        internal static string DuplicateOrganizationName {
            get {
                return ResourceManager.GetString("DuplicateOrganizationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization type name {0} has existed already!.
        /// </summary>
        internal static string DuplicateOrganizationTypeName {
            get {
                return ResourceManager.GetString("DuplicateOrganizationTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role {0} has existed in application. There only allows unique role name across organization domains in an application..
        /// </summary>
        internal static string DuplicateRoleName {
            get {
                return ResourceManager.GetString("DuplicateRoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name {0} has existed already!.
        /// </summary>
        internal static string DuplicateUserName {
            get {
                return ResourceManager.GetString("DuplicateUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area code {0} has been existed..
        /// </summary>
        internal static string ExistedAreaCode {
            get {
                return ResourceManager.GetString("ExistedAreaCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area name {0} has been existed..
        /// </summary>
        internal static string ExistedAreaName {
            get {
                return ResourceManager.GetString("ExistedAreaName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display name has been existed..
        /// </summary>
        internal static string ExistedDisplayName {
            get {
                return ResourceManager.GetString("ExistedDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization code {0} has been existed..
        /// </summary>
        internal static string ExistedOrganizationCode {
            get {
                return ResourceManager.GetString("ExistedOrganizationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization name {0} has been existed..
        /// </summary>
        internal static string ExistedOrganizationName {
            get {
                return ResourceManager.GetString("ExistedOrganizationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The organization type {0} has been existed..
        /// </summary>
        internal static string ExistedOrganizationTypeName {
            get {
                return ResourceManager.GetString("ExistedOrganizationTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role {0} has been existed..
        /// </summary>
        internal static string ExistedRoleName {
            get {
                return ResourceManager.GetString("ExistedRoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User email has been existed..
        /// </summary>
        internal static string ExistedUserEmail {
            get {
                return ResourceManager.GetString("ExistedUserEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name has been exist..
        /// </summary>
        internal static string ExistedUserName {
            get {
                return ResourceManager.GetString("ExistedUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to with children..
        /// </summary>
        internal static string HasChildArea {
            get {
                return ResourceManager.GetString("HasChildArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to without children.
        /// </summary>
        internal static string HasNoChildArea {
            get {
                return ResourceManager.GetString("HasNoChildArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hierarchy name cannot be empty!.
        /// </summary>
        internal static string HierarchyDataNameCannotBeEmpty {
            get {
                return ResourceManager.GetString("HierarchyDataNameCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hierarchy Data Object cannot be null!.
        /// </summary>
        internal static string HierarchyObjectCannotBeNull {
            get {
                return ResourceManager.GetString("HierarchyObjectCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The hierarchy type of hierarchy data cannot be changed..
        /// </summary>
        internal static string HierarchyTypeCannotBeChanged {
            get {
                return ResourceManager.GetString("HierarchyTypeCannotBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid application ID {0}..
        /// </summary>
        internal static string InvalidApplicationID {
            get {
                return ResourceManager.GetString("InvalidApplicationID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid area ID..
        /// </summary>
        internal static string InvalidAreaID {
            get {
                return ResourceManager.GetString("InvalidAreaID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The authentication is invalid..
        /// </summary>
        internal static string InvalidAuthentication {
            get {
                return ResourceManager.GetString("InvalidAuthentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid concrete data id. The concrete data may be deleted by other users before your operation..
        /// </summary>
        internal static string InvalidConcreteDataID {
            get {
                return ResourceManager.GetString("InvalidConcreteDataID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request query string parameter ConcreteDataType &quot;{0}&quot; is invalid..
        /// </summary>
        internal static string InvalidConcreteDataType {
            get {
                return ResourceManager.GetString("InvalidConcreteDataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display name should not be empty or greater than 256 characters..
        /// </summary>
        internal static string InvalidDisplayName {
            get {
                return ResourceManager.GetString("InvalidDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request query string parameter Domain &quot;{0}&quot; is invalid..
        /// </summary>
        internal static string InvalidDomain {
            get {
                return ResourceManager.GetString("InvalidDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid hierarchy &quot;{1}&quot; in type &quot;{0}&quot; associated with the organization..
        /// </summary>
        internal static string InvalidHierarchyAssociatedWithOrganization {
            get {
                return ResourceManager.GetString("InvalidHierarchyAssociatedWithOrganization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid hierarchy data id..
        /// </summary>
        internal static string InvalidHierarchyDataId {
            get {
                return ResourceManager.GetString("InvalidHierarchyDataId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Hierarchy Data Name!.
        /// </summary>
        internal static string InvalidHierarchyDataName {
            get {
                return ResourceManager.GetString("InvalidHierarchyDataName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid hierarchy type &quot;{0}&quot;..
        /// </summary>
        internal static string InvalidHierarchyType {
            get {
                return ResourceManager.GetString("InvalidHierarchyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The old password is invalid!.
        /// </summary>
        internal static string InvalidOldPasswordWhenChangePassword {
            get {
                return ResourceManager.GetString("InvalidOldPasswordWhenChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The organization of the user is invalid..
        /// </summary>
        internal static string InvalidOrganizationCredential {
            get {
                return ResourceManager.GetString("InvalidOrganizationCredential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid organization domain..
        /// </summary>
        internal static string InvalidOrganizationDomain {
            get {
                return ResourceManager.GetString("InvalidOrganizationDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid organization ID..
        /// </summary>
        internal static string InvalidOrganizationID {
            get {
                return ResourceManager.GetString("InvalidOrganizationID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid domain {0} of organization type..
        /// </summary>
        internal static string InvalidOrganizationTypeDomain {
            get {
                return ResourceManager.GetString("InvalidOrganizationTypeDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization type ID is invalid..
        /// </summary>
        internal static string InvalidOrganizationTypeID {
            get {
                return ResourceManager.GetString("InvalidOrganizationTypeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent area ID is invalid..
        /// </summary>
        internal static string InvalidParentAreaID {
            get {
                return ResourceManager.GetString("InvalidParentAreaID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid parent hierarchy data id..
        /// </summary>
        internal static string InvalidParentHierarchyDataId {
            get {
                return ResourceManager.GetString("InvalidParentHierarchyDataId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified parent organization is invalid..
        /// </summary>
        internal static string InvalidParentOrganizationID {
            get {
                return ResourceManager.GetString("InvalidParentOrganizationID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is not allowed format..
        /// </summary>
        internal static string InvalidPasswordFormat {
            get {
                return ResourceManager.GetString("InvalidPasswordFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid role ID..
        /// </summary>
        internal static string InvalidRoleID {
            get {
                return ResourceManager.GetString("InvalidRoleID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The credential is invalid..
        /// </summary>
        internal static string InvalidUserCredential {
            get {
                return ResourceManager.GetString("InvalidUserCredential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User email should not be greater than 256 characters..
        /// </summary>
        internal static string InvalidUserEmail {
            get {
                return ResourceManager.GetString("InvalidUserEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to user ID {0} is invalid..
        /// </summary>
        internal static string InvalidUserID {
            get {
                return ResourceManager.GetString("InvalidUserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name should not be empty or greater than 256 characters..
        /// </summary>
        internal static string InvalidUserName {
            get {
                return ResourceManager.GetString("InvalidUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has no parent.
        /// </summary>
        internal static string NoParentArea {
            get {
                return ResourceManager.GetString("NoParentArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization cannot be empty!.
        /// </summary>
        internal static string OrganizationCannotBeEmpty {
            get {
                return ResourceManager.GetString("OrganizationCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization code cannot be empty!.
        /// </summary>
        internal static string OrganizationCodeCannotBeEmpty {
            get {
                return ResourceManager.GetString("OrganizationCodeCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization name cannot be empty!.
        /// </summary>
        internal static string OrganizationNameCannotBeEmpty {
            get {
                return ResourceManager.GetString("OrganizationNameCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization Profile.
        /// </summary>
        internal static string OrganizationProfile {
            get {
                return ResourceManager.GetString("OrganizationProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The status of organization {2} cannot be set to {3} higher than {1} of its parent {0}..
        /// </summary>
        internal static string OrganizationStatusCannotBeHigherThanParent {
            get {
                return ResourceManager.GetString("OrganizationStatusCannotBeHigherThanParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization status is not specified..
        /// </summary>
        internal static string OrganizationStatusNotSpecified {
            get {
                return ResourceManager.GetString("OrganizationStatusNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization type cannot be empty!.
        /// </summary>
        internal static string OrganizationTypeCannotBeEmpty {
            get {
                return ResourceManager.GetString("OrganizationTypeCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization type domain cannot be empty!.
        /// </summary>
        internal static string OrganizationTypeDomainCannotBeEmpty {
            get {
                return ResourceManager.GetString("OrganizationTypeDomainCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization type name cannot be empty!.
        /// </summary>
        internal static string OrganizationTypeNameCannotBeEmpty {
            get {
                return ResourceManager.GetString("OrganizationTypeNameCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent: {0}.
        /// </summary>
        internal static string ParentArea {
            get {
                return ResourceManager.GetString("ParentArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parent organization has circular reference as {0}..
        /// </summary>
        internal static string ParentOrganizationCircularReference {
            get {
                return ResourceManager.GetString("ParentOrganizationCircularReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password answer cannot be empty..
        /// </summary>
        internal static string PasswordAnswerCannotBeEmpty {
            get {
                return ResourceManager.GetString("PasswordAnswerCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password answer should not be greater than 256 characters..
        /// </summary>
        internal static string PasswordAnswerInvalidLength {
            get {
                return ResourceManager.GetString("PasswordAnswerInvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password answer is too long..
        /// </summary>
        internal static string PasswordAnswerTooLong {
            get {
                return ResourceManager.GetString("PasswordAnswerTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password cannot be empty!.
        /// </summary>
        internal static string PasswordCannotBeEmpty {
            get {
                return ResourceManager.GetString("PasswordCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is invalid - not match the format {0}!.
        /// </summary>
        internal static string PasswordFormatIsInvalid {
            get {
                return ResourceManager.GetString("PasswordFormatIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password should not be empty or greater than 128 characters..
        /// </summary>
        internal static string PasswordInvalid {
            get {
                return ResourceManager.GetString("PasswordInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password length cannot be less than {0} characters!.
        /// </summary>
        internal static string PasswordLengthLessThanRequired {
            get {
                return ResourceManager.GetString("PasswordLengthLessThanRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password length should not be less than {0} characters..
        /// </summary>
        internal static string PasswordLessThanMinLength {
            get {
                return ResourceManager.GetString("PasswordLessThanMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password contains less than {0} non alphanumeric characters..
        /// </summary>
        internal static string PasswordLessThanMinRequiredNonAlphanumericCharacters {
            get {
                return ResourceManager.GetString("PasswordLessThanMinRequiredNonAlphanumericCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is not equal to password confirm!.
        /// </summary>
        internal static string PasswordNotEqualToConfirmPassword {
            get {
                return ResourceManager.GetString("PasswordNotEqualToConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password question cannot be empty for user..
        /// </summary>
        internal static string PasswordQuestionCannotBeEmpty {
            get {
                return ResourceManager.GetString("PasswordQuestionCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password question should not be greater than 256 characters..
        /// </summary>
        internal static string PasswordQuestionInvalidLength {
            get {
                return ResourceManager.GetString("PasswordQuestionInvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is too long..
        /// </summary>
        internal static string PasswordTooLong {
            get {
                return ResourceManager.GetString("PasswordTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role name cannot be empty!.
        /// </summary>
        internal static string RoleNameCannotBeEmpty {
            get {
                return ResourceManager.GetString("RoleNameCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request is not authorized..
        /// </summary>
        internal static string UnauthorizedAccess {
            get {
                return ResourceManager.GetString("UnauthorizedAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User email cannot be empty..
        /// </summary>
        internal static string UserEmailCannotBeEmpty {
            get {
                return ResourceManager.GetString("UserEmailCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User email should not be greater than 256 characters..
        /// </summary>
        internal static string UserEmailCannotBeGreaterThan256Characters {
            get {
                return ResourceManager.GetString("UserEmailCannotBeGreaterThan256Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user is locked out by too many failed password attempts..
        /// </summary>
        internal static string UserHasBeenLockedOut {
            get {
                return ResourceManager.GetString("UserHasBeenLockedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name cannot be empty!.
        /// </summary>
        internal static string UserNameCannotBeEmpty {
            get {
                return ResourceManager.GetString("UserNameCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Object cannot be null!.
        /// </summary>
        internal static string UserObjectCannotBeNull {
            get {
                return ResourceManager.GetString("UserObjectCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Profile.
        /// </summary>
        internal static string UserProfile {
            get {
                return ResourceManager.GetString("UserProfile", resourceCulture);
            }
        }
    }
}
