//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4200
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RapidWebDev.RestfulServices.OrganizationServices {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrganizationDomainObject", Namespace="http://www.rapidwebdev.org/platform")]
    [System.SerializableAttribute()]
    public partial class OrganizationDomainObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Text {
            get {
                return this.TextField;
            }
            set {
                if ((object.ReferenceEquals(this.TextField, value) != true)) {
                    this.TextField = value;
                    this.RaisePropertyChanged("Text");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrganizationTypeObject", Namespace="http://www.rapidwebdev.org/platform")]
    [System.SerializableAttribute()]
    public partial class OrganizationTypeObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RapidWebDev.RestfulServices.OrganizationServices.DeleteStatus DeleteStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DomainField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LastUpdatedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid OrganizationTypeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PredefinedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RapidWebDev.RestfulServices.OrganizationServices.DeleteStatus DeleteStatus {
            get {
                return this.DeleteStatusField;
            }
            set {
                if ((this.DeleteStatusField.Equals(value) != true)) {
                    this.DeleteStatusField = value;
                    this.RaisePropertyChanged("DeleteStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Domain {
            get {
                return this.DomainField;
            }
            set {
                if ((object.ReferenceEquals(this.DomainField, value) != true)) {
                    this.DomainField = value;
                    this.RaisePropertyChanged("Domain");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastUpdatedDate {
            get {
                return this.LastUpdatedDateField;
            }
            set {
                if ((this.LastUpdatedDateField.Equals(value) != true)) {
                    this.LastUpdatedDateField = value;
                    this.RaisePropertyChanged("LastUpdatedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid OrganizationTypeId {
            get {
                return this.OrganizationTypeIdField;
            }
            set {
                if ((this.OrganizationTypeIdField.Equals(value) != true)) {
                    this.OrganizationTypeIdField = value;
                    this.RaisePropertyChanged("OrganizationTypeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Predefined {
            get {
                return this.PredefinedField;
            }
            set {
                if ((this.PredefinedField.Equals(value) != true)) {
                    this.PredefinedField = value;
                    this.RaisePropertyChanged("Predefined");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeleteStatus", Namespace="http://www.rapidwebdev.org/platform")]
    public enum DeleteStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotDeleted = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Deleted = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AbstractExtensionBizObject", Namespace="http://www.rapidwebdev.org/platform")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RapidWebDev.RestfulServices.OrganizationServices.OrganizationObject))]
    public partial class AbstractExtensionBizObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid ExtensionDataTypeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<string, object> PropertiesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ExtensionDataTypeId {
            get {
                return this.ExtensionDataTypeIdField;
            }
            set {
                if ((this.ExtensionDataTypeIdField.Equals(value) != true)) {
                    this.ExtensionDataTypeIdField = value;
                    this.RaisePropertyChanged("ExtensionDataTypeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, object> Properties {
            get {
                return this.PropertiesField;
            }
            set {
                if ((object.ReferenceEquals(this.PropertiesField, value) != true)) {
                    this.PropertiesField = value;
                    this.RaisePropertyChanged("Properties");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrganizationObject", Namespace="http://www.rapidwebdev.org/platform")]
    [System.SerializableAttribute()]
    public partial class OrganizationObject : RapidWebDev.RestfulServices.OrganizationServices.AbstractExtensionBizObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid CreatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HasChildField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<string, System.Guid> HierarchiesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid LastUpdatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LastUpdatedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrganizationCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid OrganizationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrganizationNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid OrganizationTypeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.Guid> ParentOrganizationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RapidWebDev.RestfulServices.OrganizationServices.OrganizationStatus StatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid CreatedBy {
            get {
                return this.CreatedByField;
            }
            set {
                if ((this.CreatedByField.Equals(value) != true)) {
                    this.CreatedByField = value;
                    this.RaisePropertyChanged("CreatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedDate {
            get {
                return this.CreatedDateField;
            }
            set {
                if ((this.CreatedDateField.Equals(value) != true)) {
                    this.CreatedDateField = value;
                    this.RaisePropertyChanged("CreatedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasChild {
            get {
                return this.HasChildField;
            }
            set {
                if ((this.HasChildField.Equals(value) != true)) {
                    this.HasChildField = value;
                    this.RaisePropertyChanged("HasChild");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, System.Guid> Hierarchies {
            get {
                return this.HierarchiesField;
            }
            set {
                if ((object.ReferenceEquals(this.HierarchiesField, value) != true)) {
                    this.HierarchiesField = value;
                    this.RaisePropertyChanged("Hierarchies");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid LastUpdatedBy {
            get {
                return this.LastUpdatedByField;
            }
            set {
                if ((this.LastUpdatedByField.Equals(value) != true)) {
                    this.LastUpdatedByField = value;
                    this.RaisePropertyChanged("LastUpdatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastUpdatedDate {
            get {
                return this.LastUpdatedDateField;
            }
            set {
                if ((this.LastUpdatedDateField.Equals(value) != true)) {
                    this.LastUpdatedDateField = value;
                    this.RaisePropertyChanged("LastUpdatedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrganizationCode {
            get {
                return this.OrganizationCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.OrganizationCodeField, value) != true)) {
                    this.OrganizationCodeField = value;
                    this.RaisePropertyChanged("OrganizationCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid OrganizationId {
            get {
                return this.OrganizationIdField;
            }
            set {
                if ((this.OrganizationIdField.Equals(value) != true)) {
                    this.OrganizationIdField = value;
                    this.RaisePropertyChanged("OrganizationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrganizationName {
            get {
                return this.OrganizationNameField;
            }
            set {
                if ((object.ReferenceEquals(this.OrganizationNameField, value) != true)) {
                    this.OrganizationNameField = value;
                    this.RaisePropertyChanged("OrganizationName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid OrganizationTypeId {
            get {
                return this.OrganizationTypeIdField;
            }
            set {
                if ((this.OrganizationTypeIdField.Equals(value) != true)) {
                    this.OrganizationTypeIdField = value;
                    this.RaisePropertyChanged("OrganizationTypeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> ParentOrganizationId {
            get {
                return this.ParentOrganizationIdField;
            }
            set {
                if ((this.ParentOrganizationIdField.Equals(value) != true)) {
                    this.ParentOrganizationIdField = value;
                    this.RaisePropertyChanged("ParentOrganizationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RapidWebDev.RestfulServices.OrganizationServices.OrganizationStatus Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrganizationStatus", Namespace="http://www.rapidwebdev.org/platform")]
    public enum OrganizationStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Disabled = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Pending = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Enabled = 4,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="IdCollection", Namespace="http://www.rapidwebdev.org/platform", ItemName="Id")]
    [System.SerializableAttribute()]
    public class IdCollection : System.Collections.Generic.List<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="OrganizationQueryResult", Namespace="http://www.rapidwebdev.org/platform", ItemName="OrganizationObject")]
    [System.SerializableAttribute()]
    public class OrganizationQueryResult : System.Collections.Generic.List<RapidWebDev.RestfulServices.OrganizationServices.OrganizationObject> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DateTimeFieldValue", Namespace="http://www.rapidwebdev.org/extensionmodel")]
    [System.SerializableAttribute()]
    public partial class DateTimeFieldValue : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateTimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateTime {
            get {
                return this.DateTimeField;
            }
            set {
                if ((this.DateTimeField.Equals(value) != true)) {
                    this.DateTimeField = value;
                    this.RaisePropertyChanged("DateTime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DecimalFieldValue", Namespace="http://www.rapidwebdev.org/extensionmodel")]
    [System.SerializableAttribute()]
    public partial class DecimalFieldValue : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal DecimalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Decimal {
            get {
                return this.DecimalField;
            }
            set {
                if ((this.DecimalField.Equals(value) != true)) {
                    this.DecimalField = value;
                    this.RaisePropertyChanged("Decimal");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StringFieldValue", Namespace="http://www.rapidwebdev.org/extensionmodel")]
    [System.SerializableAttribute()]
    public partial class StringFieldValue : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string String {
            get {
                return this.StringField;
            }
            set {
                if ((object.ReferenceEquals(this.StringField, value) != true)) {
                    this.StringField = value;
                    this.RaisePropertyChanged("String");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IntegerFieldValue", Namespace="http://www.rapidwebdev.org/extensionmodel")]
    [System.SerializableAttribute()]
    public partial class IntegerFieldValue : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IntegerField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Integer {
            get {
                return this.IntegerField;
            }
            set {
                if ((this.IntegerField.Equals(value) != true)) {
                    this.IntegerField = value;
                    this.RaisePropertyChanged("Integer");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="EnumerationValueCollection", Namespace="http://schemas.datacontract.org/2004/07/RapidWebDev.ExtensionModel", ItemName="EnumerationValue")]
    [System.SerializableAttribute()]
    public class EnumerationValueCollection : System.Collections.Generic.List<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WebServiceQueryPredicate", Namespace="http://www.rapidwebdev.org/common")]
    [System.SerializableAttribute()]
    public partial class WebServiceQueryPredicate : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExpressionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RapidWebDev.RestfulServices.OrganizationServices.WebServiceQueryPredicateParameter[] ParametersField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Expression {
            get {
                return this.ExpressionField;
            }
            set {
                if ((object.ReferenceEquals(this.ExpressionField, value) != true)) {
                    this.ExpressionField = value;
                    this.RaisePropertyChanged("Expression");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RapidWebDev.RestfulServices.OrganizationServices.WebServiceQueryPredicateParameter[] Parameters {
            get {
                return this.ParametersField;
            }
            set {
                if ((object.ReferenceEquals(this.ParametersField, value) != true)) {
                    this.ParametersField = value;
                    this.RaisePropertyChanged("Parameters");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WebServiceQueryPredicateParameter", Namespace="http://www.rapidwebdev.org/common")]
    [System.SerializableAttribute()]
    public partial class WebServiceQueryPredicateParameter : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RapidWebDev.RestfulServices.OrganizationServices.WebServiceQueryPredicateParameterTypes TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RapidWebDev.RestfulServices.OrganizationServices.WebServiceQueryPredicateParameterTypes Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WebServiceQueryPredicateParameterTypes", Namespace="http://www.rapidwebdev.org/common")]
    public enum WebServiceQueryPredicateParameterTypes : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        String = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DateTime = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Guid = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Integer = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Decimal = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Double = 5,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.rapidwebdev.org/platform", ConfigurationName="OrganizationServices.OrganizationService")]
    public interface OrganizationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rapidwebdev.org/platform/OrganizationService/ListDomainsJson", ReplyAction="http://www.rapidwebdev.org/platform/OrganizationService/ListDomainsJsonResponse")]
        RapidWebDev.RestfulServices.OrganizationServices.OrganizationDomainObject[] ListDomainsJson();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rapidwebdev.org/platform/OrganizationService/ListDomainsXml", ReplyAction="http://www.rapidwebdev.org/platform/OrganizationService/ListDomainsXmlResponse")]
        RapidWebDev.RestfulServices.OrganizationServices.OrganizationDomainObject[] ListDomainsXml();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rapidwebdev.org/platform/OrganizationService/SaveOrganizationTypeJson", ReplyAction="http://www.rapidwebdev.org/platform/OrganizationService/SaveOrganizationTypeJsonR" +
            "esponse")]
        string SaveOrganizationTypeJson(RapidWebDev.RestfulServices.OrganizationServices.OrganizationTypeObject organizationTypeObject);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rapidwebdev.org/platform/OrganizationService/SaveOrganizationTypeXml", ReplyAction="http://www.rapidwebdev.org/platform/OrganizationService/SaveOrganizationTypeXmlRe" +
            "sponse")]
        string SaveOrganizationTypeXml(RapidWebDev.RestfulServices.OrganizationServices.OrganizationTypeObject organizationTypeObject);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rapidwebdev.org/platform/OrganizationService/GetOrganizationTypeByIdJs" +
            "on", ReplyAction="http://www.rapidwebdev.org/platform/OrganizationService/GetOrganizationTypeByIdJs" +
            "onResponse")]
        RapidWebDev.RestfulServices.OrganizationServices.OrganizationTypeObject GetOrganizationTypeByIdJson(string organizationTypeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rapidwebdev.org/platform/OrganizationService/GetOrganizationTypeByIdXm" +
            "l", ReplyAction="http://www.rapidwebdev.org/platform/OrganizationService/GetOrganizationTypeByIdXm" +
            "lResponse")]
        RapidWebDev.RestfulServices.OrganizationServices.OrganizationTypeObject GetOrganizationTypeByIdXml(string organizationTypeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rapidwebdev.org/platform/OrganizationService/GetOrganizationTypeByName" +
            "Json", ReplyAction="http://www.rapidwebdev.org/platform/OrganizationService/GetOrganizationTypeByName" +
            "JsonResponse")]
        RapidWebDev.RestfulServices.OrganizationServices.OrganizationTypeObject GetOrganizationTypeByNameJson(string organizationTypeName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rapidwebdev.org/platform/OrganizationService/GetOrganizationTypeByName" +
            "Xml", ReplyAction="http://www.rapidwebdev.org/platform/OrganizationService/GetOrganizationTypeByName" +
            "XmlResponse")]
        RapidWebDev.RestfulServices.OrganizationServices.OrganizationTypeObject GetOrganizationTypeByNameXml(string organizationTypeName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rapidwebdev.org/platform/OrganizationService/FindOrganizationTypesJson" +
            "", ReplyAction="http://www.rapidwebdev.org/platform/OrganizationService/FindOrganizationTypesJson" +
            "Response")]
        RapidWebDev.RestfulServices.OrganizationServices.OrganizationTypeObject[] FindOrganizationTypesJson(string domain);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rapidwebdev.org/platform/OrganizationService/FindOrganizationTypesXml", ReplyAction="http://www.rapidwebdev.org/platform/OrganizationService/FindOrganizationTypesXmlR" +
            "esponse")]
        RapidWebDev.RestfulServices.OrganizationServices.OrganizationTypeObject[] FindOrganizationTypesXml(string domain);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rapidwebdev.org/platform/OrganizationService/SaveOrganizationJson", ReplyAction="http://www.rapidwebdev.org/platform/OrganizationService/SaveOrganizationJsonRespo" +
            "nse")]
        string SaveOrganizationJson(RapidWebDev.RestfulServices.OrganizationServices.OrganizationObject organizationObject);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rapidwebdev.org/platform/OrganizationService/SaveOrganizationXml", ReplyAction="http://www.rapidwebdev.org/platform/OrganizationService/SaveOrganizationXmlRespon" +
            "se")]
        string SaveOrganizationXml(RapidWebDev.RestfulServices.OrganizationServices.OrganizationObject organizationObject);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rapidwebdev.org/platform/OrganizationService/GetOrganizationByIdJson", ReplyAction="http://www.rapidwebdev.org/platform/OrganizationService/GetOrganizationByIdJsonRe" +
            "sponse")]
        RapidWebDev.RestfulServices.OrganizationServices.OrganizationObject GetOrganizationByIdJson(string organizationId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rapidwebdev.org/platform/OrganizationService/GetOrganizationByIdXml", ReplyAction="http://www.rapidwebdev.org/platform/OrganizationService/GetOrganizationByIdXmlRes" +
            "ponse")]
        RapidWebDev.RestfulServices.OrganizationServices.OrganizationObject GetOrganizationByIdXml(string organizationId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rapidwebdev.org/platform/OrganizationService/GetOrganizationByCodeJson" +
            "", ReplyAction="http://www.rapidwebdev.org/platform/OrganizationService/GetOrganizationByCodeJson" +
            "Response")]
        RapidWebDev.RestfulServices.OrganizationServices.OrganizationObject GetOrganizationByCodeJson(string organizationCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rapidwebdev.org/platform/OrganizationService/GetOrganizationByCodeXml", ReplyAction="http://www.rapidwebdev.org/platform/OrganizationService/GetOrganizationByCodeXmlR" +
            "esponse")]
        RapidWebDev.RestfulServices.OrganizationServices.OrganizationObject GetOrganizationByCodeXml(string organizationCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rapidwebdev.org/platform/OrganizationService/GetOrganizationByNameJson" +
            "", ReplyAction="http://www.rapidwebdev.org/platform/OrganizationService/GetOrganizationByNameJson" +
            "Response")]
        RapidWebDev.RestfulServices.OrganizationServices.OrganizationObject GetOrganizationByNameJson(string organizationName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rapidwebdev.org/platform/OrganizationService/GetOrganizationByNameXml", ReplyAction="http://www.rapidwebdev.org/platform/OrganizationService/GetOrganizationByNameXmlR" +
            "esponse")]
        RapidWebDev.RestfulServices.OrganizationServices.OrganizationObject GetOrganizationByNameXml(string organizationName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rapidwebdev.org/platform/OrganizationService/BulkGetOrganizationsByIds" +
            "Json", ReplyAction="http://www.rapidwebdev.org/platform/OrganizationService/BulkGetOrganizationsByIds" +
            "JsonResponse")]
        RapidWebDev.RestfulServices.OrganizationServices.OrganizationObject[] BulkGetOrganizationsByIdsJson(RapidWebDev.RestfulServices.OrganizationServices.IdCollection organizationIdList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rapidwebdev.org/platform/OrganizationService/BulkGetOrganizationsByIds" +
            "Xml", ReplyAction="http://www.rapidwebdev.org/platform/OrganizationService/BulkGetOrganizationsByIds" +
            "XmlResponse")]
        RapidWebDev.RestfulServices.OrganizationServices.OrganizationObject[] BulkGetOrganizationsByIdsXml(RapidWebDev.RestfulServices.OrganizationServices.IdCollection organizationIdList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rapidwebdev.org/platform/OrganizationService/SearchJson", ReplyAction="http://www.rapidwebdev.org/platform/OrganizationService/SearchJsonResponse")]
        RapidWebDev.RestfulServices.OrganizationServices.OrganizationQueryResult SearchJson(string domain, string orgTypeId, string q, string sortField, string sortDirection, int start, int limit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rapidwebdev.org/platform/OrganizationService/SearchXml", ReplyAction="http://www.rapidwebdev.org/platform/OrganizationService/SearchXmlResponse")]
        RapidWebDev.RestfulServices.OrganizationServices.OrganizationQueryResult SearchXml(string domain, string orgTypeId, string q, string sortField, string sortDirection, int start, int limit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rapidwebdev.org/platform/OrganizationService/QueryOrganizationsJson", ReplyAction="http://www.rapidwebdev.org/platform/OrganizationService/QueryOrganizationsJsonRes" +
            "ponse")]
        RapidWebDev.RestfulServices.OrganizationServices.OrganizationQueryResult QueryOrganizationsJson(string orderby, int pageIndex, int pageSize, RapidWebDev.RestfulServices.OrganizationServices.WebServiceQueryPredicate predicate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rapidwebdev.org/platform/OrganizationService/QueryOrganizationsXml", ReplyAction="http://www.rapidwebdev.org/platform/OrganizationService/QueryOrganizationsXmlResp" +
            "onse")]
        RapidWebDev.RestfulServices.OrganizationServices.OrganizationQueryResult QueryOrganizationsXml(string orderby, int pageIndex, int pageSize, RapidWebDev.RestfulServices.OrganizationServices.WebServiceQueryPredicate predicate);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface OrganizationServiceChannel : RapidWebDev.RestfulServices.OrganizationServices.OrganizationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class OrganizationServiceClient : System.ServiceModel.ClientBase<RapidWebDev.RestfulServices.OrganizationServices.OrganizationService>, RapidWebDev.RestfulServices.OrganizationServices.OrganizationService {
        
        public OrganizationServiceClient() {
        }
        
        public OrganizationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OrganizationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrganizationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrganizationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public RapidWebDev.RestfulServices.OrganizationServices.OrganizationDomainObject[] ListDomainsJson() {
            return base.Channel.ListDomainsJson();
        }
        
        public RapidWebDev.RestfulServices.OrganizationServices.OrganizationDomainObject[] ListDomainsXml() {
            return base.Channel.ListDomainsXml();
        }
        
        public string SaveOrganizationTypeJson(RapidWebDev.RestfulServices.OrganizationServices.OrganizationTypeObject organizationTypeObject) {
            return base.Channel.SaveOrganizationTypeJson(organizationTypeObject);
        }
        
        public string SaveOrganizationTypeXml(RapidWebDev.RestfulServices.OrganizationServices.OrganizationTypeObject organizationTypeObject) {
            return base.Channel.SaveOrganizationTypeXml(organizationTypeObject);
        }
        
        public RapidWebDev.RestfulServices.OrganizationServices.OrganizationTypeObject GetOrganizationTypeByIdJson(string organizationTypeId) {
            return base.Channel.GetOrganizationTypeByIdJson(organizationTypeId);
        }
        
        public RapidWebDev.RestfulServices.OrganizationServices.OrganizationTypeObject GetOrganizationTypeByIdXml(string organizationTypeId) {
            return base.Channel.GetOrganizationTypeByIdXml(organizationTypeId);
        }
        
        public RapidWebDev.RestfulServices.OrganizationServices.OrganizationTypeObject GetOrganizationTypeByNameJson(string organizationTypeName) {
            return base.Channel.GetOrganizationTypeByNameJson(organizationTypeName);
        }
        
        public RapidWebDev.RestfulServices.OrganizationServices.OrganizationTypeObject GetOrganizationTypeByNameXml(string organizationTypeName) {
            return base.Channel.GetOrganizationTypeByNameXml(organizationTypeName);
        }
        
        public RapidWebDev.RestfulServices.OrganizationServices.OrganizationTypeObject[] FindOrganizationTypesJson(string domain) {
            return base.Channel.FindOrganizationTypesJson(domain);
        }
        
        public RapidWebDev.RestfulServices.OrganizationServices.OrganizationTypeObject[] FindOrganizationTypesXml(string domain) {
            return base.Channel.FindOrganizationTypesXml(domain);
        }
        
        public string SaveOrganizationJson(RapidWebDev.RestfulServices.OrganizationServices.OrganizationObject organizationObject) {
            return base.Channel.SaveOrganizationJson(organizationObject);
        }
        
        public string SaveOrganizationXml(RapidWebDev.RestfulServices.OrganizationServices.OrganizationObject organizationObject) {
            return base.Channel.SaveOrganizationXml(organizationObject);
        }
        
        public RapidWebDev.RestfulServices.OrganizationServices.OrganizationObject GetOrganizationByIdJson(string organizationId) {
            return base.Channel.GetOrganizationByIdJson(organizationId);
        }
        
        public RapidWebDev.RestfulServices.OrganizationServices.OrganizationObject GetOrganizationByIdXml(string organizationId) {
            return base.Channel.GetOrganizationByIdXml(organizationId);
        }
        
        public RapidWebDev.RestfulServices.OrganizationServices.OrganizationObject GetOrganizationByCodeJson(string organizationCode) {
            return base.Channel.GetOrganizationByCodeJson(organizationCode);
        }
        
        public RapidWebDev.RestfulServices.OrganizationServices.OrganizationObject GetOrganizationByCodeXml(string organizationCode) {
            return base.Channel.GetOrganizationByCodeXml(organizationCode);
        }
        
        public RapidWebDev.RestfulServices.OrganizationServices.OrganizationObject GetOrganizationByNameJson(string organizationName) {
            return base.Channel.GetOrganizationByNameJson(organizationName);
        }
        
        public RapidWebDev.RestfulServices.OrganizationServices.OrganizationObject GetOrganizationByNameXml(string organizationName) {
            return base.Channel.GetOrganizationByNameXml(organizationName);
        }
        
        public RapidWebDev.RestfulServices.OrganizationServices.OrganizationObject[] BulkGetOrganizationsByIdsJson(RapidWebDev.RestfulServices.OrganizationServices.IdCollection organizationIdList) {
            return base.Channel.BulkGetOrganizationsByIdsJson(organizationIdList);
        }
        
        public RapidWebDev.RestfulServices.OrganizationServices.OrganizationObject[] BulkGetOrganizationsByIdsXml(RapidWebDev.RestfulServices.OrganizationServices.IdCollection organizationIdList) {
            return base.Channel.BulkGetOrganizationsByIdsXml(organizationIdList);
        }
        
        public RapidWebDev.RestfulServices.OrganizationServices.OrganizationQueryResult SearchJson(string domain, string orgTypeId, string q, string sortField, string sortDirection, int start, int limit) {
            return base.Channel.SearchJson(domain, orgTypeId, q, sortField, sortDirection, start, limit);
        }
        
        public RapidWebDev.RestfulServices.OrganizationServices.OrganizationQueryResult SearchXml(string domain, string orgTypeId, string q, string sortField, string sortDirection, int start, int limit) {
            return base.Channel.SearchXml(domain, orgTypeId, q, sortField, sortDirection, start, limit);
        }
        
        public RapidWebDev.RestfulServices.OrganizationServices.OrganizationQueryResult QueryOrganizationsJson(string orderby, int pageIndex, int pageSize, RapidWebDev.RestfulServices.OrganizationServices.WebServiceQueryPredicate predicate) {
            return base.Channel.QueryOrganizationsJson(orderby, pageIndex, pageSize, predicate);
        }
        
        public RapidWebDev.RestfulServices.OrganizationServices.OrganizationQueryResult QueryOrganizationsXml(string orderby, int pageIndex, int pageSize, RapidWebDev.RestfulServices.OrganizationServices.WebServiceQueryPredicate predicate) {
            return base.Channel.QueryOrganizationsXml(orderby, pageIndex, pageSize, predicate);
        }
    }
}
