//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 
namespace RapidWebDev.ExtensionModel {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.rapidwebdev.org/schemas/extensionmodel")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.rapidwebdev.org/schemas/extensionmodel", IsNullable=false)]
    public partial class StringFieldMetadata : FieldMetadataBase {
        
        private int maxLengthField;
        
        private bool maxLengthFieldSpecified;
        
        private int minLengthField;
        
        private bool minLengthFieldSpecified;
        
        private string regexField;
        
        private string defaultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int MaxLength {
            get {
                return this.maxLengthField;
            }
            set {
                this.maxLengthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MaxLengthSpecified {
            get {
                return this.maxLengthFieldSpecified;
            }
            set {
                this.maxLengthFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int MinLength {
            get {
                return this.minLengthField;
            }
            set {
                this.minLengthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MinLengthSpecified {
            get {
                return this.minLengthFieldSpecified;
            }
            set {
                this.minLengthFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Regex {
            get {
                return this.regexField;
            }
            set {
                this.regexField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Default {
            get {
                return this.defaultField;
            }
            set {
                this.defaultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(HierarchyFieldMetadata))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EnumerationFieldMetadata))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DecimalFieldMetadata))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IntegerFieldMetadata))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DateTimeFieldMetadata))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DateFieldMetadata))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(StringFieldMetadata))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.rapidwebdev.org/schemas/extensionmodel")]
    public abstract partial class FieldMetadataBase {
        
        private string nameField;
        
        private string fieldGroupField;
        
        private bool isRequiredField;
        
        private int ordinalField;
        
        private FieldPriviledges priviledgeField;
        
		/// <summary />
        public FieldMetadataBase() {
            this.isRequiredField = false;
            this.ordinalField = 10000;
            this.priviledgeField = FieldPriviledges.Public;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FieldGroup {
            get {
                return this.fieldGroupField;
            }
            set {
                this.fieldGroupField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool IsRequired {
            get {
                return this.isRequiredField;
            }
            set {
                this.isRequiredField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(10000)]
        public int Ordinal {
            get {
                return this.ordinalField;
            }
            set {
                this.ordinalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(FieldPriviledges.Public)]
        public FieldPriviledges Priviledge {
            get {
                return this.priviledgeField;
            }
            set {
                this.priviledgeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.rapidwebdev.org/schemas/extensionmodel")]
    public enum FieldPriviledges {
        
        /// <remarks/>
        Public,
        
        /// <remarks/>
        EditProtectedOnly,
        
        /// <remarks/>
        BothEditAndViewProtected,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.rapidwebdev.org/schemas/extensionmodel")]
    public partial class HierarchyNode {
        
        private HierarchyNode[] nodeField;
        
        private string nameField;
        
        private string valueField;
        
        private bool selectedField;

		/// <summary />
        public HierarchyNode() {
            this.selectedField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Node")]
        public HierarchyNode[] Node {
            get {
                return this.nodeField;
            }
            set {
                this.nodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool Selected {
            get {
                return this.selectedField;
            }
            set {
                this.selectedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.rapidwebdev.org/schemas/extensionmodel")]
    public partial class SelectionItem {
        
        private string nameField;
        
        private string valueField;
        
        private bool selectedField;

		/// <summary />
        public SelectionItem() {
            this.selectedField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool Selected {
            get {
                return this.selectedField;
            }
            set {
                this.selectedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.rapidwebdev.org/schemas/extensionmodel")]
    public partial class DateTimeValue {
        
        private System.DateTime valueField;
        
        private bool valueFieldSpecified;
        
        private DateTimeValueTypes dateTimeValueTypeField;

		/// <summary />
        public DateTimeValue() {
            this.dateTimeValueTypeField = DateTimeValueTypes.Custom;
        }
        
        /// <remarks/>
        public System.DateTime Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValueSpecified {
            get {
                return this.valueFieldSpecified;
            }
            set {
                this.valueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(DateTimeValueTypes.Custom)]
        public DateTimeValueTypes DateTimeValueType {
            get {
                return this.dateTimeValueTypeField;
            }
            set {
                this.dateTimeValueTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.rapidwebdev.org/schemas/extensionmodel")]
    public enum DateTimeValueTypes {
        
        /// <remarks/>
        Now,
        
        /// <remarks/>
        Custom,
        
        /// <remarks/>
        FirstDayOfThisYear,
        
        /// <remarks/>
        FirstDayOfThisMonth,
        
        /// <remarks/>
        FirstDayOfThisWeek,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.rapidwebdev.org/schemas/extensionmodel")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.rapidwebdev.org/schemas/extensionmodel", IsNullable=false)]
    public partial class DateTimeFieldMetadata : FieldMetadataBase {
        
        private DateTimeValue defaultValueField;
        
        private DateTimeValue maxValueField;
        
        private DateTimeValue minValueField;
        
        /// <remarks/>
        public DateTimeValue DefaultValue {
            get {
                return this.defaultValueField;
            }
            set {
                this.defaultValueField = value;
            }
        }
        
        /// <remarks/>
        public DateTimeValue MaxValue {
            get {
                return this.maxValueField;
            }
            set {
                this.maxValueField = value;
            }
        }
        
        /// <remarks/>
        public DateTimeValue MinValue {
            get {
                return this.minValueField;
            }
            set {
                this.minValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.rapidwebdev.org/schemas/extensionmodel")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.rapidwebdev.org/schemas/extensionmodel", IsNullable=false)]
    public partial class DateFieldMetadata : FieldMetadataBase {
        
        private DateTimeValue defaultValueField;
        
        private DateTimeValue maxValueField;
        
        private DateTimeValue minValueField;
        
        /// <remarks/>
        public DateTimeValue DefaultValue {
            get {
                return this.defaultValueField;
            }
            set {
                this.defaultValueField = value;
            }
        }
        
        /// <remarks/>
        public DateTimeValue MaxValue {
            get {
                return this.maxValueField;
            }
            set {
                this.maxValueField = value;
            }
        }
        
        /// <remarks/>
        public DateTimeValue MinValue {
            get {
                return this.minValueField;
            }
            set {
                this.minValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.rapidwebdev.org/schemas/extensionmodel")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.rapidwebdev.org/schemas/extensionmodel", IsNullable=false)]
    public partial class IntegerFieldMetadata : FieldMetadataBase {
        
        private int maxValueField;
        
        private bool maxValueFieldSpecified;
        
        private int minValueField;
        
        private bool minValueFieldSpecified;
        
        private int defaultField;
        
        private bool defaultFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int MaxValue {
            get {
                return this.maxValueField;
            }
            set {
                this.maxValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MaxValueSpecified {
            get {
                return this.maxValueFieldSpecified;
            }
            set {
                this.maxValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int MinValue {
            get {
                return this.minValueField;
            }
            set {
                this.minValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MinValueSpecified {
            get {
                return this.minValueFieldSpecified;
            }
            set {
                this.minValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Default {
            get {
                return this.defaultField;
            }
            set {
                this.defaultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DefaultSpecified {
            get {
                return this.defaultFieldSpecified;
            }
            set {
                this.defaultFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.rapidwebdev.org/schemas/extensionmodel")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.rapidwebdev.org/schemas/extensionmodel", IsNullable=false)]
    public partial class DecimalFieldMetadata : FieldMetadataBase {
        
        private decimal maxValueField;
        
        private bool maxValueFieldSpecified;
        
        private decimal minValueField;
        
        private bool minValueFieldSpecified;
        
        private decimal defaultField;
        
        private bool defaultFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal MaxValue {
            get {
                return this.maxValueField;
            }
            set {
                this.maxValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MaxValueSpecified {
            get {
                return this.maxValueFieldSpecified;
            }
            set {
                this.maxValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal MinValue {
            get {
                return this.minValueField;
            }
            set {
                this.minValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MinValueSpecified {
            get {
                return this.minValueFieldSpecified;
            }
            set {
                this.minValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal Default {
            get {
                return this.defaultField;
            }
            set {
                this.defaultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DefaultSpecified {
            get {
                return this.defaultFieldSpecified;
            }
            set {
                this.defaultFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.rapidwebdev.org/schemas/extensionmodel")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.rapidwebdev.org/schemas/extensionmodel", IsNullable=false)]
    public partial class EnumerationFieldMetadata : FieldMetadataBase {
        
        private SelectionItem[] itemsField;
        
        private SelectionModes selectionModeField;

		/// <summary />
        public EnumerationFieldMetadata() {
            this.selectionModeField = SelectionModes.Multiple;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Items")]
        public SelectionItem[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(SelectionModes.Multiple)]
        public SelectionModes SelectionMode {
            get {
                return this.selectionModeField;
            }
            set {
                this.selectionModeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.rapidwebdev.org/schemas/extensionmodel")]
    public enum SelectionModes {
        
        /// <remarks/>
        Multiple,
        
        /// <remarks/>
        Single,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.rapidwebdev.org/schemas/extensionmodel")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.rapidwebdev.org/schemas/extensionmodel", IsNullable=false)]
    public partial class HierarchyFieldMetadata : FieldMetadataBase {
        
        private HierarchyNode[] nodeField;
        
        private SelectionModes selectionModeField;

		/// <summary />
        public HierarchyFieldMetadata() {
            this.selectionModeField = SelectionModes.Multiple;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Node")]
        public HierarchyNode[] Node {
            get {
                return this.nodeField;
            }
            set {
                this.nodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(SelectionModes.Multiple)]
        public SelectionModes SelectionMode {
            get {
                return this.selectionModeField;
            }
            set {
                this.selectionModeField = value;
            }
        }
    }
}
