//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4200
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RapidWebDev.RestfulServices.SequenceServices {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.rapidwebdev.org/platform", ConfigurationName="SequenceServices.SequenceService")]
    public interface SequenceService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rapidwebdev.org/platform/SequenceService/CreateSingleJson", ReplyAction="http://www.rapidwebdev.org/platform/SequenceService/CreateSingleJsonResponse")]
        long CreateSingleJson(string objectId, string sequenceNoType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rapidwebdev.org/platform/SequenceService/CreateSingleXml", ReplyAction="http://www.rapidwebdev.org/platform/SequenceService/CreateSingleXmlResponse")]
        long CreateSingleXml(string objectId, string sequenceNoType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rapidwebdev.org/platform/SequenceService/CreateMultipleJson", ReplyAction="http://www.rapidwebdev.org/platform/SequenceService/CreateMultipleJsonResponse")]
        long[] CreateMultipleJson(string objectId, string sequenceNoType, string sequenceNoCount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rapidwebdev.org/platform/SequenceService/CreateMultipleXml", ReplyAction="http://www.rapidwebdev.org/platform/SequenceService/CreateMultipleXmlResponse")]
        long[] CreateMultipleXml(string objectId, string sequenceNoType, string sequenceNoCount);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface SequenceServiceChannel : RapidWebDev.RestfulServices.SequenceServices.SequenceService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class SequenceServiceClient : System.ServiceModel.ClientBase<RapidWebDev.RestfulServices.SequenceServices.SequenceService>, RapidWebDev.RestfulServices.SequenceServices.SequenceService {
        
        public SequenceServiceClient() {
        }
        
        public SequenceServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SequenceServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SequenceServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SequenceServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public long CreateSingleJson(string objectId, string sequenceNoType) {
            return base.Channel.CreateSingleJson(objectId, sequenceNoType);
        }
        
        public long CreateSingleXml(string objectId, string sequenceNoType) {
            return base.Channel.CreateSingleXml(objectId, sequenceNoType);
        }
        
        public long[] CreateMultipleJson(string objectId, string sequenceNoType, string sequenceNoCount) {
            return base.Channel.CreateMultipleJson(objectId, sequenceNoType, sequenceNoCount);
        }
        
        public long[] CreateMultipleXml(string objectId, string sequenceNoType, string sequenceNoCount) {
            return base.Channel.CreateMultipleXml(objectId, sequenceNoType, sequenceNoCount);
        }
    }
}
