//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RapidWebDev.Common.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RapidWebDev.Common.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad Request..
        /// </summary>
        internal static string BadRequest {
            get {
                return ResourceManager.GetString("BadRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection type {0} is invalid IDbConnection type..
        /// </summary>
        internal static string ConnectionTypeInvalidIDbConnectionType {
            get {
                return ResourceManager.GetString("ConnectionTypeInvalidIDbConnectionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection type {0} is not found..
        /// </summary>
        internal static string ConnectionTypeNotFound {
            get {
                return ResourceManager.GetString("ConnectionTypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attemption to convert string value {0} to explicit type {1} failed..
        /// </summary>
        internal static string ConvertTypeFailed {
            get {
                return ResourceManager.GetString("ConvertTypeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MMM d, yyyy.
        /// </summary>
        internal static string DateFormatString {
            get {
                return ResourceManager.GetString("DateFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MMM d, yyyy HH:mm.
        /// </summary>
        internal static string DateTimeFormatString {
            get {
                return ResourceManager.GetString("DateTimeFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad Request. Deserialization failed. Please make sure the request document is well formed..
        /// </summary>
        internal static string DeserializationFailMessage {
            get {
                return ResourceManager.GetString("DeserializationFailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel document doesn&apos;t exist..
        /// </summary>
        internal static string ExcelDocumentNotExist {
            get {
                return ResourceManager.GetString("ExcelDocumentNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server encountered an error while processing the request. Refer to server logs for more details..
        /// </summary>
        internal static string InternalServerErrorMessage {
            get {
                return ResourceManager.GetString("InternalServerErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid excel document due to unexpected columns number..
        /// </summary>
        internal static string InvalidExcelDocumentWithUnpredictableColunmNumber {
            get {
                return ResourceManager.GetString("InvalidExcelDocumentWithUnpredictableColunmNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid excel format..
        /// </summary>
        internal static string InvalidExcelFormat {
            get {
                return ResourceManager.GetString("InvalidExcelFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The globalization variable &quot;{0}&quot; is invalid format to $NameSpace.Class.Property, AssemblyName$. .
        /// </summary>
        internal static string InvalidFormatGlobalizationVariable {
            get {
                return ResourceManager.GetString("InvalidFormatGlobalizationVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Found..
        /// </summary>
        internal static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server encountered an error while processing the request..
        /// </summary>
        internal static string RestfulErrorMessage {
            get {
                return ResourceManager.GetString("RestfulErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type {0} is not implemented in current executing application domain..
        /// </summary>
        internal static string TypeNotImplementedInDomain {
            get {
                return ResourceManager.GetString("TypeNotImplementedInDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized Request..
        /// </summary>
        internal static string Unauthorized {
            get {
                return ResourceManager.GetString("Unauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string WebServerTimeZoneName {
            get {
                return ResourceManager.GetString("WebServerTimeZoneName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified xml document doesn&apos;t include namespace {0}..
        /// </summary>
        internal static string XmlDocumentNotIncludeSpecifiedNamespace {
            get {
                return ResourceManager.GetString("XmlDocumentNotIncludeSpecifiedNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} is thrown at line {1}, postion {2} of specified xml file. The validation fails by \&quot;{3}\&quot;\r\n\r\n.
        /// </summary>
        internal static string XmlValidationFail {
            get {
                return ResourceManager.GetString("XmlValidationFail", resourceCulture);
            }
        }
    }
}
