//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4200
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RapidWebDev.RestfulServices.RoleServices {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RoleObject", Namespace="http://www.rapidwebdev.org/platform")]
    [System.SerializableAttribute()]
    public partial class RoleObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DomainField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PredefinedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid RoleIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoleNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Domain {
            get {
                return this.DomainField;
            }
            set {
                if ((object.ReferenceEquals(this.DomainField, value) != true)) {
                    this.DomainField = value;
                    this.RaisePropertyChanged("Domain");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Predefined {
            get {
                return this.PredefinedField;
            }
            set {
                if ((this.PredefinedField.Equals(value) != true)) {
                    this.PredefinedField = value;
                    this.RaisePropertyChanged("Predefined");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid RoleId {
            get {
                return this.RoleIdField;
            }
            set {
                if ((this.RoleIdField.Equals(value) != true)) {
                    this.RoleIdField = value;
                    this.RaisePropertyChanged("RoleId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RoleName {
            get {
                return this.RoleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.RoleNameField, value) != true)) {
                    this.RoleNameField = value;
                    this.RaisePropertyChanged("RoleName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="IdCollection", Namespace="http://www.rapidwebdev.org/platform", ItemName="Id")]
    [System.SerializableAttribute()]
    public class IdCollection : System.Collections.Generic.List<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WebServiceQueryPredicate", Namespace="http://www.rapidwebdev.org/common")]
    [System.SerializableAttribute()]
    public partial class WebServiceQueryPredicate : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExpressionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RapidWebDev.RestfulServices.RoleServices.WebServiceQueryPredicateParameter[] ParametersField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Expression {
            get {
                return this.ExpressionField;
            }
            set {
                if ((object.ReferenceEquals(this.ExpressionField, value) != true)) {
                    this.ExpressionField = value;
                    this.RaisePropertyChanged("Expression");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RapidWebDev.RestfulServices.RoleServices.WebServiceQueryPredicateParameter[] Parameters {
            get {
                return this.ParametersField;
            }
            set {
                if ((object.ReferenceEquals(this.ParametersField, value) != true)) {
                    this.ParametersField = value;
                    this.RaisePropertyChanged("Parameters");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WebServiceQueryPredicateParameter", Namespace="http://www.rapidwebdev.org/common")]
    [System.SerializableAttribute()]
    public partial class WebServiceQueryPredicateParameter : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RapidWebDev.RestfulServices.RoleServices.WebServiceQueryPredicateParameterTypes TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RapidWebDev.RestfulServices.RoleServices.WebServiceQueryPredicateParameterTypes Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WebServiceQueryPredicateParameterTypes", Namespace="http://www.rapidwebdev.org/common")]
    public enum WebServiceQueryPredicateParameterTypes : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        String = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DateTime = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Guid = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Integer = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Decimal = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Double = 5,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="RoleQueryResult", Namespace="http://www.rapidwebdev.org/platform", ItemName="RoleObject")]
    [System.SerializableAttribute()]
    public class RoleQueryResult : System.Collections.Generic.List<RapidWebDev.RestfulServices.RoleServices.RoleObject> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.rapidwebdev.org/platform", ConfigurationName="RoleServices.RoleService")]
    public interface RoleService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rapidwebdev.org/platform/RoleService/SaveJson", ReplyAction="http://www.rapidwebdev.org/platform/RoleService/SaveJsonResponse")]
        string SaveJson(RapidWebDev.RestfulServices.RoleServices.RoleObject roleObject);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rapidwebdev.org/platform/RoleService/SaveXml", ReplyAction="http://www.rapidwebdev.org/platform/RoleService/SaveXmlResponse")]
        string SaveXml(RapidWebDev.RestfulServices.RoleServices.RoleObject roleObject);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rapidwebdev.org/platform/RoleService/HardDeleteJson", ReplyAction="http://www.rapidwebdev.org/platform/RoleService/HardDeleteJsonResponse")]
        void HardDeleteJson(string roleId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rapidwebdev.org/platform/RoleService/HardDeleteXml", ReplyAction="http://www.rapidwebdev.org/platform/RoleService/HardDeleteXmlResponse")]
        void HardDeleteXml(string roleId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rapidwebdev.org/platform/RoleService/SetUserToRolesJson", ReplyAction="http://www.rapidwebdev.org/platform/RoleService/SetUserToRolesJsonResponse")]
        void SetUserToRolesJson(string userId, RapidWebDev.RestfulServices.RoleServices.IdCollection roleIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rapidwebdev.org/platform/RoleService/SetUserToRolesXml", ReplyAction="http://www.rapidwebdev.org/platform/RoleService/SetUserToRolesXmlResponse")]
        void SetUserToRolesXml(string userId, RapidWebDev.RestfulServices.RoleServices.IdCollection roleIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rapidwebdev.org/platform/RoleService/GetByNameJson", ReplyAction="http://www.rapidwebdev.org/platform/RoleService/GetByNameJsonResponse")]
        RapidWebDev.RestfulServices.RoleServices.RoleObject GetByNameJson(string roleName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rapidwebdev.org/platform/RoleService/GetByNameXml", ReplyAction="http://www.rapidwebdev.org/platform/RoleService/GetByNameXmlResponse")]
        RapidWebDev.RestfulServices.RoleServices.RoleObject GetByNameXml(string roleName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rapidwebdev.org/platform/RoleService/GetByIdJson", ReplyAction="http://www.rapidwebdev.org/platform/RoleService/GetByIdJsonResponse")]
        RapidWebDev.RestfulServices.RoleServices.RoleObject GetByIdJson(string roleId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rapidwebdev.org/platform/RoleService/GetByIdXml", ReplyAction="http://www.rapidwebdev.org/platform/RoleService/GetByIdXmlResponse")]
        RapidWebDev.RestfulServices.RoleServices.RoleObject GetByIdXml(string roleId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rapidwebdev.org/platform/RoleService/BulkGetJson", ReplyAction="http://www.rapidwebdev.org/platform/RoleService/BulkGetJsonResponse")]
        RapidWebDev.RestfulServices.RoleServices.RoleObject[] BulkGetJson(RapidWebDev.RestfulServices.RoleServices.IdCollection roleIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rapidwebdev.org/platform/RoleService/BulkGetXml", ReplyAction="http://www.rapidwebdev.org/platform/RoleService/BulkGetXmlResponse")]
        RapidWebDev.RestfulServices.RoleServices.RoleObject[] BulkGetXml(RapidWebDev.RestfulServices.RoleServices.IdCollection roleIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rapidwebdev.org/platform/RoleService/FindAllJson", ReplyAction="http://www.rapidwebdev.org/platform/RoleService/FindAllJsonResponse")]
        RapidWebDev.RestfulServices.RoleServices.RoleObject[] FindAllJson();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rapidwebdev.org/platform/RoleService/FindAllXml", ReplyAction="http://www.rapidwebdev.org/platform/RoleService/FindAllXmlResponse")]
        RapidWebDev.RestfulServices.RoleServices.RoleObject[] FindAllXml();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rapidwebdev.org/platform/RoleService/FindByOrganizationIdJson", ReplyAction="http://www.rapidwebdev.org/platform/RoleService/FindByOrganizationIdJsonResponse")]
        RapidWebDev.RestfulServices.RoleServices.RoleObject[] FindByOrganizationIdJson(string organizationId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rapidwebdev.org/platform/RoleService/FindByOrganizationIdXml", ReplyAction="http://www.rapidwebdev.org/platform/RoleService/FindByOrganizationIdXmlResponse")]
        RapidWebDev.RestfulServices.RoleServices.RoleObject[] FindByOrganizationIdXml(string organizationId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rapidwebdev.org/platform/RoleService/FindByUserIdJson", ReplyAction="http://www.rapidwebdev.org/platform/RoleService/FindByUserIdJsonResponse")]
        RapidWebDev.RestfulServices.RoleServices.RoleObject[] FindByUserIdJson(string userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rapidwebdev.org/platform/RoleService/FindByUserIdXml", ReplyAction="http://www.rapidwebdev.org/platform/RoleService/FindByUserIdXmlResponse")]
        RapidWebDev.RestfulServices.RoleServices.RoleObject[] FindByUserIdXml(string userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rapidwebdev.org/platform/RoleService/FindByOrganizationTypeJson", ReplyAction="http://www.rapidwebdev.org/platform/RoleService/FindByOrganizationTypeJsonRespons" +
            "e")]
        RapidWebDev.RestfulServices.RoleServices.RoleObject[] FindByOrganizationTypeJson(string organizationTypeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rapidwebdev.org/platform/RoleService/FindByOrganizationTypeXml", ReplyAction="http://www.rapidwebdev.org/platform/RoleService/FindByOrganizationTypeXmlResponse" +
            "")]
        RapidWebDev.RestfulServices.RoleServices.RoleObject[] FindByOrganizationTypeXml(string organizationTypeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rapidwebdev.org/platform/RoleService/FindByDomainJson", ReplyAction="http://www.rapidwebdev.org/platform/RoleService/FindByDomainJsonResponse")]
        RapidWebDev.RestfulServices.RoleServices.RoleObject[] FindByDomainJson(string domain);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rapidwebdev.org/platform/RoleService/FindByDomainXml", ReplyAction="http://www.rapidwebdev.org/platform/RoleService/FindByDomainXmlResponse")]
        RapidWebDev.RestfulServices.RoleServices.RoleObject[] FindByDomainXml(string domain);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rapidwebdev.org/platform/RoleService/IsUserInRoleByIdJson", ReplyAction="http://www.rapidwebdev.org/platform/RoleService/IsUserInRoleByIdJsonResponse")]
        bool IsUserInRoleByIdJson(string userId, string roleId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rapidwebdev.org/platform/RoleService/IsUserInRoleByIdXml", ReplyAction="http://www.rapidwebdev.org/platform/RoleService/IsUserInRoleByIdXmlResponse")]
        bool IsUserInRoleByIdXml(string userId, string roleId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rapidwebdev.org/platform/RoleService/IsUserInRoleByNameJson", ReplyAction="http://www.rapidwebdev.org/platform/RoleService/IsUserInRoleByNameJsonResponse")]
        bool IsUserInRoleByNameJson(string userId, string roleName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rapidwebdev.org/platform/RoleService/IsUserInRoleByNameXml", ReplyAction="http://www.rapidwebdev.org/platform/RoleService/IsUserInRoleByNameXmlResponse")]
        bool IsUserInRoleByNameXml(string userId, string roleName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rapidwebdev.org/platform/RoleService/QueryRolesJson", ReplyAction="http://www.rapidwebdev.org/platform/RoleService/QueryRolesJsonResponse")]
        RapidWebDev.RestfulServices.RoleServices.RoleQueryResult QueryRolesJson(string orderby, int pageIndex, int pageSize, RapidWebDev.RestfulServices.RoleServices.WebServiceQueryPredicate predicate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rapidwebdev.org/platform/RoleService/QueryRolesXml", ReplyAction="http://www.rapidwebdev.org/platform/RoleService/QueryRolesXmlResponse")]
        RapidWebDev.RestfulServices.RoleServices.RoleQueryResult QueryRolesXml(string orderby, int pageIndex, int pageSize, RapidWebDev.RestfulServices.RoleServices.WebServiceQueryPredicate predicate);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface RoleServiceChannel : RapidWebDev.RestfulServices.RoleServices.RoleService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class RoleServiceClient : System.ServiceModel.ClientBase<RapidWebDev.RestfulServices.RoleServices.RoleService>, RapidWebDev.RestfulServices.RoleServices.RoleService {
        
        public RoleServiceClient() {
        }
        
        public RoleServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RoleServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RoleServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RoleServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string SaveJson(RapidWebDev.RestfulServices.RoleServices.RoleObject roleObject) {
            return base.Channel.SaveJson(roleObject);
        }
        
        public string SaveXml(RapidWebDev.RestfulServices.RoleServices.RoleObject roleObject) {
            return base.Channel.SaveXml(roleObject);
        }
        
        public void HardDeleteJson(string roleId) {
            base.Channel.HardDeleteJson(roleId);
        }
        
        public void HardDeleteXml(string roleId) {
            base.Channel.HardDeleteXml(roleId);
        }
        
        public void SetUserToRolesJson(string userId, RapidWebDev.RestfulServices.RoleServices.IdCollection roleIds) {
            base.Channel.SetUserToRolesJson(userId, roleIds);
        }
        
        public void SetUserToRolesXml(string userId, RapidWebDev.RestfulServices.RoleServices.IdCollection roleIds) {
            base.Channel.SetUserToRolesXml(userId, roleIds);
        }
        
        public RapidWebDev.RestfulServices.RoleServices.RoleObject GetByNameJson(string roleName) {
            return base.Channel.GetByNameJson(roleName);
        }
        
        public RapidWebDev.RestfulServices.RoleServices.RoleObject GetByNameXml(string roleName) {
            return base.Channel.GetByNameXml(roleName);
        }
        
        public RapidWebDev.RestfulServices.RoleServices.RoleObject GetByIdJson(string roleId) {
            return base.Channel.GetByIdJson(roleId);
        }
        
        public RapidWebDev.RestfulServices.RoleServices.RoleObject GetByIdXml(string roleId) {
            return base.Channel.GetByIdXml(roleId);
        }
        
        public RapidWebDev.RestfulServices.RoleServices.RoleObject[] BulkGetJson(RapidWebDev.RestfulServices.RoleServices.IdCollection roleIds) {
            return base.Channel.BulkGetJson(roleIds);
        }
        
        public RapidWebDev.RestfulServices.RoleServices.RoleObject[] BulkGetXml(RapidWebDev.RestfulServices.RoleServices.IdCollection roleIds) {
            return base.Channel.BulkGetXml(roleIds);
        }
        
        public RapidWebDev.RestfulServices.RoleServices.RoleObject[] FindAllJson() {
            return base.Channel.FindAllJson();
        }
        
        public RapidWebDev.RestfulServices.RoleServices.RoleObject[] FindAllXml() {
            return base.Channel.FindAllXml();
        }
        
        public RapidWebDev.RestfulServices.RoleServices.RoleObject[] FindByOrganizationIdJson(string organizationId) {
            return base.Channel.FindByOrganizationIdJson(organizationId);
        }
        
        public RapidWebDev.RestfulServices.RoleServices.RoleObject[] FindByOrganizationIdXml(string organizationId) {
            return base.Channel.FindByOrganizationIdXml(organizationId);
        }
        
        public RapidWebDev.RestfulServices.RoleServices.RoleObject[] FindByUserIdJson(string userId) {
            return base.Channel.FindByUserIdJson(userId);
        }
        
        public RapidWebDev.RestfulServices.RoleServices.RoleObject[] FindByUserIdXml(string userId) {
            return base.Channel.FindByUserIdXml(userId);
        }
        
        public RapidWebDev.RestfulServices.RoleServices.RoleObject[] FindByOrganizationTypeJson(string organizationTypeId) {
            return base.Channel.FindByOrganizationTypeJson(organizationTypeId);
        }
        
        public RapidWebDev.RestfulServices.RoleServices.RoleObject[] FindByOrganizationTypeXml(string organizationTypeId) {
            return base.Channel.FindByOrganizationTypeXml(organizationTypeId);
        }
        
        public RapidWebDev.RestfulServices.RoleServices.RoleObject[] FindByDomainJson(string domain) {
            return base.Channel.FindByDomainJson(domain);
        }
        
        public RapidWebDev.RestfulServices.RoleServices.RoleObject[] FindByDomainXml(string domain) {
            return base.Channel.FindByDomainXml(domain);
        }
        
        public bool IsUserInRoleByIdJson(string userId, string roleId) {
            return base.Channel.IsUserInRoleByIdJson(userId, roleId);
        }
        
        public bool IsUserInRoleByIdXml(string userId, string roleId) {
            return base.Channel.IsUserInRoleByIdXml(userId, roleId);
        }
        
        public bool IsUserInRoleByNameJson(string userId, string roleName) {
            return base.Channel.IsUserInRoleByNameJson(userId, roleName);
        }
        
        public bool IsUserInRoleByNameXml(string userId, string roleName) {
            return base.Channel.IsUserInRoleByNameXml(userId, roleName);
        }
        
        public RapidWebDev.RestfulServices.RoleServices.RoleQueryResult QueryRolesJson(string orderby, int pageIndex, int pageSize, RapidWebDev.RestfulServices.RoleServices.WebServiceQueryPredicate predicate) {
            return base.Channel.QueryRolesJson(orderby, pageIndex, pageSize, predicate);
        }
        
        public RapidWebDev.RestfulServices.RoleServices.RoleQueryResult QueryRolesXml(string orderby, int pageIndex, int pageSize, RapidWebDev.RestfulServices.RoleServices.WebServiceQueryPredicate predicate) {
            return base.Channel.QueryRolesXml(orderby, pageIndex, pageSize, predicate);
        }
    }
}
