//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RapidWebDev.FileManagement.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RapidWebDev.FileManagement.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property &quot;FileCategory&quot; of FileManagementControl cannot be empty..
        /// </summary>
        internal static string FileCategoryCannotBeEmpty {
            get {
                return ResourceManager.GetString("FileCategoryCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The querystring parameter &quot;category&quot; not found..
        /// </summary>
        internal static string FileCategoryQueryStringParameterNotFound {
            get {
                return ResourceManager.GetString("FileCategoryQueryStringParameterNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file cannot be found in the server..
        /// </summary>
        internal static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to remove this file?.
        /// </summary>
        internal static string FileRemoveConfirmationMessage {
            get {
                return ResourceManager.GetString("FileRemoveConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Upload Dialog.
        /// </summary>
        internal static string FileUploadDialogTitle {
            get {
                return ResourceManager.GetString("FileUploadDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click the button below to select uploading file locally..
        /// </summary>
        internal static string FileUploadToolTip {
            get {
                return ResourceManager.GetString("FileUploadToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid external object id..
        /// </summary>
        internal static string InvalidExternalObjectId {
            get {
                return ResourceManager.GetString("InvalidExternalObjectId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request Uri doesn&apos;t follow the file download Uri template &quot;FileDownload.svc/fileid/{fileid}&quot;..
        /// </summary>
        internal static string InvalidFileDownloadUri {
            get {
                return ResourceManager.GetString("InvalidFileDownloadUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file id..
        /// </summary>
        internal static string InvalidFileId {
            get {
                return ResourceManager.GetString("InvalidFileId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property &quot;FileSharedPath&quot; of FileStorageApi is not configured..
        /// </summary>
        internal static string InvalidFileSharedPath {
            get {
                return ResourceManager.GetString("InvalidFileSharedPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The query string parameter &quot;ext&quot; is not specified..
        /// </summary>
        internal static string InvalidQueryStringParameterExt {
            get {
                return ResourceManager.GetString("InvalidQueryStringParameterExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permission to download files..
        /// </summary>
        internal static string NoPermissionToDownloadFiles {
            get {
                return ResourceManager.GetString("NoPermissionToDownloadFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permission to upload files..
        /// </summary>
        internal static string NoPermissionToUploadFiles {
            get {
                return ResourceManager.GetString("NoPermissionToUploadFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload More.
        /// </summary>
        internal static string ShowUploadDialogButtonText {
            get {
                return ResourceManager.GetString("ShowUploadDialogButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error occurs in the server..
        /// </summary>
        internal static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The uploading file stream is not readable..
        /// </summary>
        internal static string UnreadableFileStream {
            get {
                return ResourceManager.GetString("UnreadableFileStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        internal static string UploadButtonText {
            get {
                return ResourceManager.GetString("UploadButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string UploadCancelButtonText {
            get {
                return ResourceManager.GetString("UploadCancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No uploaded file found..
        /// </summary>
        internal static string UploadingFileNotFound {
            get {
                return ResourceManager.GetString("UploadingFileNotFound", resourceCulture);
            }
        }
    }
}
