//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RapidWebDev.UI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RapidWebDev.UI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string Ctrl_AspnetPager_AllText {
            get {
                return ResourceManager.GetString("Ctrl_AspnetPager_AllText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The page index is invalid..
        /// </summary>
        internal static string Ctrl_AspnetPager_InvalidPageIndex {
            get {
                return ResourceManager.GetString("Ctrl_AspnetPager_InvalidPageIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs error while creating controls. The detail exception is: .
        /// </summary>
        internal static string Ctrl_AspnetPager_OccurErrorWhenCreateControls {
            get {
                return ResourceManager.GetString("Ctrl_AspnetPager_OccurErrorWhenCreateControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The page number is out of index..
        /// </summary>
        internal static string Ctrl_AspnetPager_PageNumberOutOfIndex {
            get {
                return ResourceManager.GetString("Ctrl_AspnetPager_PageNumberOutOfIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string Ctrl_AspnetPager_SubmitText {
            get {
                return ResourceManager.GetString("Ctrl_AspnetPager_SubmitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Ctrl_CloseButtonText {
            get {
                return ResourceManager.GetString("Ctrl_CloseButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string Ctrl_ComboBoxLoadingText {
            get {
                return ResourceManager.GetString("Ctrl_ComboBoxLoadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y-m-d.
        /// </summary>
        internal static string Ctrl_DatePicker_DateFormatString {
            get {
                return ResourceManager.GetString("Ctrl_DatePicker_DateFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose hour.
        /// </summary>
        internal static string Ctrl_DateTimePicker_ChooseHourText {
            get {
                return ResourceManager.GetString("Ctrl_DateTimePicker_ChooseHourText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Minute.
        /// </summary>
        internal static string Ctrl_DateTimePicker_ChooseMinuteText {
            get {
                return ResourceManager.GetString("Ctrl_DateTimePicker_ChooseMinuteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y-m-d H:i.
        /// </summary>
        internal static string Ctrl_DateTimePicker_DateTimeFormatString {
            get {
                return ResourceManager.GetString("Ctrl_DateTimePicker_DateTimeFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H.
        /// </summary>
        internal static string Ctrl_DateTimePicker_HourText {
            get {
                return ResourceManager.GetString("Ctrl_DateTimePicker_HourText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M.
        /// </summary>
        internal static string Ctrl_DateTimePicker_MinuteText {
            get {
                return ResourceManager.GetString("Ctrl_DateTimePicker_MinuteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Hour.
        /// </summary>
        internal static string Ctrl_DateTimePicker_NextHourText {
            get {
                return ResourceManager.GetString("Ctrl_DateTimePicker_NextHourText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Minute.
        /// </summary>
        internal static string Ctrl_DateTimePicker_NextMinuteText {
            get {
                return ResourceManager.GetString("Ctrl_DateTimePicker_NextMinuteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now.
        /// </summary>
        internal static string Ctrl_DateTimePicker_NowText {
            get {
                return ResourceManager.GetString("Ctrl_DateTimePicker_NowText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Hour.
        /// </summary>
        internal static string Ctrl_DateTimePicker_PreviousHourText {
            get {
                return ResourceManager.GetString("Ctrl_DateTimePicker_PreviousHourText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Minute.
        /// </summary>
        internal static string Ctrl_DateTimePicker_PreviousMinuteText {
            get {
                return ResourceManager.GetString("Ctrl_DateTimePicker_PreviousMinuteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The feature of FlashUpload control is not specified..
        /// </summary>
        internal static string Ctrl_FlashUploadFeatureNotSpecified {
            get {
                return ResourceManager.GetString("Ctrl_FlashUploadFeatureNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Type.
        /// </summary>
        internal static string Ctrl_FlashUploadFileType {
            get {
                return ResourceManager.GetString("Ctrl_FlashUploadFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No control found by the property &quot;CallbackControlId&quot;..
        /// </summary>
        internal static string Ctrl_NoControlFoundByCallbackControlId {
            get {
                return ResourceManager.GetString("Ctrl_NoControlFoundByCallbackControlId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization Profile.
        /// </summary>
        internal static string Ctrl_OrganizationLink_OrganizationText {
            get {
                return ResourceManager.GetString("Ctrl_OrganizationLink_OrganizationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property &quot;CallbackControlId&quot; cannot be null or empty..
        /// </summary>
        internal static string Ctrl_PropertyCallbackControlIdCannotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("Ctrl_PropertyCallbackControlIdCannotBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property configuration is not specified..
        /// </summary>
        internal static string Ctrl_PropertyConfigurationNotSpecified {
            get {
                return ResourceManager.GetString("Ctrl_PropertyConfigurationNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property &quot;ObjectId&quot; cannot be null or empty..
        /// </summary>
        internal static string Ctrl_PropertyObjectIdCannotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("Ctrl_PropertyObjectIdCannotBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query.
        /// </summary>
        internal static string Ctrl_QueryButtonText {
            get {
                return ResourceManager.GetString("Ctrl_QueryButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The query string &quot;Feature&quot; is not specified..
        /// </summary>
        internal static string Ctrl_QueryStringFeatureNotSpecified {
            get {
                return ResourceManager.GetString("Ctrl_QueryStringFeatureNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The query string &quot;UploadingIdentifier&quot; is not specified..
        /// </summary>
        internal static string Ctrl_QueryStringUploadingIdIdentifierNotSpecified {
            get {
                return ResourceManager.GetString("Ctrl_QueryStringUploadingIdIdentifierNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string Ctrl_ResetButtonText {
            get {
                return ResourceManager.GetString("Ctrl_ResetButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Profile.
        /// </summary>
        internal static string Ctrl_UserLink_UserText {
            get {
                return ResourceManager.GetString("Ctrl_UserLink_UserText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ascending.
        /// </summary>
        internal static string DP_Ascending {
            get {
                return ResourceManager.GetString("DP_Ascending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value for QueryFieldOperators.Between must implement IEnumerable with two items..
        /// </summary>
        internal static string DP_BetweenValueMustBeEnumerableWithTwoItems {
            get {
                return ResourceManager.GetString("DP_BetweenValueMustBeEnumerableWithTwoItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified configuration file [{0}] doesn&apos;t exist..
        /// </summary>
        internal static string DP_ConfigurationFileNotExists {
            get {
                return ResourceManager.GetString("DP_ConfigurationFileNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors occured while initializing configuration object from the configuration file {0}..
        /// </summary>
        internal static string DP_ConfigurationFileParsedIncorrect {
            get {
                return ResourceManager.GetString("DP_ConfigurationFileParsedIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configured dynamic page type {0} for object {1} doesn&apos;t exist..
        /// </summary>
        internal static string DP_ConfiguredDynamicPageTypeNotExists {
            get {
                return ResourceManager.GetString("DP_ConfiguredDynamicPageTypeNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configured dynamic page type {0} for object {1} doesn&apos;t implement the interface IDynamicPage..
        /// </summary>
        internal static string DP_ConfiguredDynamicPageTypeNotImplementIDynamicPage {
            get {
                return ResourceManager.GetString("DP_ConfiguredDynamicPageTypeNotImplementIDynamicPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configured form panel type {0} for object {1} doesn&apos;t exist..
        /// </summary>
        internal static string DP_ConfiguredFormPanelTypeNotExists {
            get {
                return ResourceManager.GetString("DP_ConfiguredFormPanelTypeNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configured form panel type {0} for object {1} doesn&apos;t implement the interface IDynamicComponent..
        /// </summary>
        internal static string DP_ConfiguredFormPanelTypeNotImplementIDynamicComponent {
            get {
                return ResourceManager.GetString("DP_ConfiguredFormPanelTypeNotImplementIDynamicComponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configured IGridViewFieldValueTransformCallback implementation type {0} doesn&apos;t exist..
        /// </summary>
        internal static string DP_ConfiguredTransformCallbackTypeNotExists {
            get {
                return ResourceManager.GetString("DP_ConfiguredTransformCallbackTypeNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not supported control configuration element {0}..
        /// </summary>
        internal static string DP_ControlElementNotSupported {
            get {
                return ResourceManager.GetString("DP_ControlElementNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The control type {0} is not supported..
        /// </summary>
        internal static string DP_ControlTypeNotSupported {
            get {
                return ResourceManager.GetString("DP_ControlTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The post value {0} cannot be converted to {1} properly..
        /// </summary>
        internal static string DP_ControlValueConvertFailedMessage {
            get {
                return ResourceManager.GetString("DP_ControlValueConvertFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The IControlValueResolver with name &quot;{0}&quot; is not configured properly..
        /// </summary>
        internal static string DP_ControlValueResolverUnavailable {
            get {
                return ResourceManager.GetString("DP_ControlValueResolverUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descending.
        /// </summary>
        internal static string DP_Descending {
            get {
                return ResourceManager.GetString("DP_Descending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified ParentControlPath &quot;{0}&quot; is invalid in the template file..
        /// </summary>
        internal static string DP_DetailPanel_InvalidParentControlPath {
            get {
                return ResourceManager.GetString("DP_DetailPanel_InvalidParentControlPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate command argument &quot;{0}&quot; of aggregate panel configured in the dynamic page..
        /// </summary>
        internal static string DP_DuplicateAggregatePanelCommandArgumentConfigured {
            get {
                return ResourceManager.GetString("DP_DuplicateAggregatePanelCommandArgumentConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate configuration object [{0}]..
        /// </summary>
        internal static string DP_DuplicateConfigurationObject {
            get {
                return ResourceManager.GetString("DP_DuplicateConfigurationObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displaying {0} issues as at {1} by {2}..
        /// </summary>
        internal static string DP_DynamicPage_Print_HeadBar_Template {
            get {
                return ResourceManager.GetString("DP_DynamicPage_Print_HeadBar_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The framework cannot recognize specified field name {0} correctly..
        /// </summary>
        internal static string DP_GridFieldNameInvalid {
            get {
                return ResourceManager.GetString("DP_GridFieldNameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently the framework doesn&apos;t support indexer property binding {0}. The workaround is to create an Dictionary typed property to store key-value pairs in indexer property..
        /// </summary>
        internal static string DP_IndexerGridFieldNameNotSupported {
            get {
                return ResourceManager.GetString("DP_IndexerGridFieldNameNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string DP_InformationText {
            get {
                return ResourceManager.GetString("DP_InformationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configured aggregate panel type &quot;{0}&quot; for the command argument &quot;{1}&quot; of the dynamic page is invalid or doesn&apos;t implement the interface IAggregatePanelPage..
        /// </summary>
        internal static string DP_InvalidAggregatePanelType {
            get {
                return ResourceManager.GetString("DP_InvalidAggregatePanelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid configuration file [{0}] schema..
        /// </summary>
        internal static string DP_InvalidConfigurationFileSchema {
            get {
                return ResourceManager.GetString("DP_InvalidConfigurationFileSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configured detail panel type &quot;{0}&quot; of the dynamic page is invalid or doesn&apos;t implement the interface IDetailPanelPage..
        /// </summary>
        internal static string DP_InvalidDetailPanelType {
            get {
                return ResourceManager.GetString("DP_InvalidDetailPanelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value {0} of table item style {1} is invalid..
        /// </summary>
        internal static string DP_InvalidTableItemStyleConfiguration {
            get {
                return ResourceManager.GetString("DP_InvalidTableItemStyleConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There only allows maximum one detail panel configured in a dynamic page..
        /// </summary>
        internal static string DP_MultipleDetailPanelConfigured {
            get {
                return ResourceManager.GetString("DP_MultipleDetailPanelConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There only allows maximum one gridview panel configured in a dynamic page..
        /// </summary>
        internal static string DP_MultipleGridViewPanelConfigured {
            get {
                return ResourceManager.GetString("DP_MultipleGridViewPanelConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There only allows maximum one query panel configured in a dynamic page..
        /// </summary>
        internal static string DP_MultipleQueryPanelConfigured {
            get {
                return ResourceManager.GetString("DP_MultipleQueryPanelConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The IDynamicPage instance with Id [{0}] is not configured..
        /// </summary>
        internal static string DP_ObjectIdNotConfigured {
            get {
                return ResourceManager.GetString("DP_ObjectIdNotConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The records are sorted by &quot;{0}&quot; in {1}..
        /// </summary>
        internal static string DP_PrintResultSortingDescription {
            get {
                return ResourceManager.GetString("DP_PrintResultSortingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to compares with.
        /// </summary>
        internal static string DP_QueryFieldOperator_Auto {
            get {
                return ResourceManager.GetString("DP_QueryFieldOperator_Auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is between.
        /// </summary>
        internal static string DP_QueryFieldOperator_Between {
            get {
                return ResourceManager.GetString("DP_QueryFieldOperator_Between", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to equals to.
        /// </summary>
        internal static string DP_QueryFieldOperator_Equal {
            get {
                return ResourceManager.GetString("DP_QueryFieldOperator_Equal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is greater equal than.
        /// </summary>
        internal static string DP_QueryFieldOperator_GreaterEqualThan {
            get {
                return ResourceManager.GetString("DP_QueryFieldOperator_GreaterEqualThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is greater than.
        /// </summary>
        internal static string DP_QueryFieldOperator_GreaterThan {
            get {
                return ResourceManager.GetString("DP_QueryFieldOperator_GreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is in.
        /// </summary>
        internal static string DP_QueryFieldOperator_In {
            get {
                return ResourceManager.GetString("DP_QueryFieldOperator_In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is less equal than.
        /// </summary>
        internal static string DP_QueryFieldOperator_LessEqualThan {
            get {
                return ResourceManager.GetString("DP_QueryFieldOperator_LessEqualThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is less than.
        /// </summary>
        internal static string DP_QueryFieldOperator_LessThan {
            get {
                return ResourceManager.GetString("DP_QueryFieldOperator_LessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to likes.
        /// </summary>
        internal static string DP_QueryFieldOperator_Like {
            get {
                return ResourceManager.GetString("DP_QueryFieldOperator_Like", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is not in.
        /// </summary>
        internal static string DP_QueryFieldOperator_NotIn {
            get {
                return ResourceManager.GetString("DP_QueryFieldOperator_NotIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to starts with.
        /// </summary>
        internal static string DP_QueryFieldOperator_StartsWith {
            get {
                return ResourceManager.GetString("DP_QueryFieldOperator_StartsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The layout element {0} in query panel is not supported..
        /// </summary>
        internal static string DP_QueryPanelLayoutNotSupported {
            get {
                return ResourceManager.GetString("DP_QueryPanelLayoutNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra.
        /// </summary>
        internal static string DP_RowView_HeaderText {
            get {
                return ResourceManager.GetString("DP_RowView_HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved successfully!.
        /// </summary>
        internal static string DP_SavedSuccessfullyMessage {
            get {
                return ResourceManager.GetString("DP_SavedSuccessfullyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The access is unauthorized due to you have not logged on or your authentication ticket has been expired..
        /// </summary>
        internal static string DP_UnauthorizedAccess {
            get {
                return ResourceManager.GetString("DP_UnauthorizedAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error is occured and it has been logged, please try it later or contact the system administrator..
        /// </summary>
        internal static string DP_UnknownErrorDetail {
            get {
                return ResourceManager.GetString("DP_UnknownErrorDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The variable ${0}$ defined in &quot;{1}&quot; doesn&apos;t exist in IApplicationContext.TempVariables..
        /// </summary>
        internal static string DP_VariableNotExistInCurrentContext {
            get {
                return ResourceManager.GetString("DP_VariableNotExistInCurrentContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string DP_WarningText {
            get {
                return ResourceManager.GetString("DP_WarningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string DPCtrl_CancelText {
            get {
                return ResourceManager.GetString("DPCtrl_CancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configured Custom control type {0} not found..
        /// </summary>
        internal static string DPCtrl_CustomControlTypeNotFound {
            get {
                return ResourceManager.GetString("DPCtrl_CustomControlTypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete this record?.
        /// </summary>
        internal static string DPCtrl_DeleteButtonClientConfirmMessage {
            get {
                return ResourceManager.GetString("DPCtrl_DeleteButtonClientConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string DPCtrl_DeleteText {
            get {
                return ResourceManager.GetString("DPCtrl_DeleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string DPCtrl_EditText {
            get {
                return ResourceManager.GetString("DPCtrl_EditText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The checkbox checked in column header means that all records by the query includes not displayed ones in this grid page will be processed together..
        /// </summary>
        internal static string DPCtrl_Grid_ColumnHeadCheckBoxToolTip {
            get {
                return ResourceManager.GetString("DPCtrl_Grid_ColumnHeadCheckBoxToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Confirmation.
        /// </summary>
        internal static string DPCtrl_Grid_DeleteConfirmDialogTitle {
            get {
                return ResourceManager.GetString("DPCtrl_Grid_DeleteConfirmDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete the {0}?.
        /// </summary>
        internal static string DPCtrl_Grid_DeleteConfirmMessageTemplate {
            get {
                return ResourceManager.GetString("DPCtrl_Grid_DeleteConfirmMessageTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No {0} found by the query..
        /// </summary>
        internal static string DPCtrl_Grid_EmptyGridPanelMessageTemplate {
            get {
                return ResourceManager.GetString("DPCtrl_Grid_EmptyGridPanelMessageTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displaying {EntityName} from {0} to {1} of total {2}..
        /// </summary>
        internal static string DPCtrl_Grid_PagingDisplayMessageTemplate {
            get {
                return ResourceManager.GetString("DPCtrl_Grid_PagingDisplayMessageTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Preview.
        /// </summary>
        internal static string DPCtrl_Grid_PreviewButtonText {
            get {
                return ResourceManager.GetString("DPCtrl_Grid_PreviewButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configured Custom control type {0} doesn&apos;t implement the interface IQueryFieldControl..
        /// </summary>
        internal static string DPCtrl_InvalidCustomControlType {
            get {
                return ResourceManager.GetString("DPCtrl_InvalidCustomControlType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading, please wait for a while..
        /// </summary>
        internal static string DPCtrl_LoadingText {
            get {
                return ResourceManager.GetString("DPCtrl_LoadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control Index {0} of posted value is invalid..
        /// </summary>
        internal static string DPCtrl_PostedValueControlIndexInvalid {
            get {
                return ResourceManager.GetString("DPCtrl_PostedValueControlIndexInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        internal static string DPCtrl_QueryFieldControl_Between_Separator {
            get {
                return ResourceManager.GetString("DPCtrl_QueryFieldControl_Between_Separator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified query field control type {0} is not supported..
        /// </summary>
        internal static string DPCtrl_QueryFieldControlNotSupport {
            get {
                return ResourceManager.GetString("DPCtrl_QueryFieldControlNotSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save &amp; Add Another.
        /// </summary>
        internal static string DPCtrl_SaveAndAddAnotherText {
            get {
                return ResourceManager.GetString("DPCtrl_SaveAndAddAnotherText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save &amp; Close.
        /// </summary>
        internal static string DPCtrl_SaveAndCloseText {
            get {
                return ResourceManager.GetString("DPCtrl_SaveAndCloseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string DPCtrl_SaveText {
            get {
                return ResourceManager.GetString("DPCtrl_SaveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selector.
        /// </summary>
        internal static string DPCtrl_Selector {
            get {
                return ResourceManager.GetString("DPCtrl_Selector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        internal static string DPCtrl_SummaryText {
            get {
                return ResourceManager.GetString("DPCtrl_SummaryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified template skin file {0} doesn&apos;t exist..
        /// </summary>
        internal static string DPCtrl_TemplateSkinFileNotExists {
            get {
                return ResourceManager.GetString("DPCtrl_TemplateSkinFileNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string DPCtrl_ViewText {
            get {
                return ResourceManager.GetString("DPCtrl_ViewText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load remote data failed..
        /// </summary>
        internal static string DTCtrl_LoadRemoteDataFailed {
            get {
                return ResourceManager.GetString("DTCtrl_LoadRemoteDataFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RapidWebDev - The Key To Speed Up Your Business..
        /// </summary>
        internal static string FP_DefaultPageTitle {
            get {
                return ResourceManager.GetString("FP_DefaultPageTitle", resourceCulture);
            }
        }
    }
}
